/*
 * EasyBimehLanding.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using EasyBimehLanding.Standard;
using EasyBimehLanding.Standard.Utilities;


namespace EasyBimehLanding.Standard.Models
{
    public class DeviceBrandTypes : BaseModel 
    {
        // These fields hold the values for the public properties.
        private int id;
        private string title;
        private int deviceGroup;
        private int? deviceTypeId;
        private string deviceBrandId;
        private string createOn;
        private string updateOn;
        private string createdBy;
        private string updatedBy;
        private string createOnPersianDate;
        private string updateOnPersianDate;
        private string deviceTypeTitle;
        private string deviceBrandTitle;
        private string deviceTypeBrandModelTitle;
        private List<string> deviceBrandIds;
        private string deviceBrandsTitle;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("id")]
        public int Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("title")]
        public string Title 
        { 
            get 
            {
                return this.title; 
            } 
            set 
            {
                this.title = value;
                onPropertyChanged("Title");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("deviceGroup")]
        public int DeviceGroup 
        { 
            get 
            {
                return this.deviceGroup; 
            } 
            set 
            {
                this.deviceGroup = value;
                onPropertyChanged("DeviceGroup");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("deviceTypeId")]
        public int? DeviceTypeId 
        { 
            get 
            {
                return this.deviceTypeId; 
            } 
            set 
            {
                this.deviceTypeId = value;
                onPropertyChanged("DeviceTypeId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("deviceBrandId")]
        public string DeviceBrandId 
        { 
            get 
            {
                return this.deviceBrandId; 
            } 
            set 
            {
                this.deviceBrandId = value;
                onPropertyChanged("DeviceBrandId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("createOn")]
        public string CreateOn 
        { 
            get 
            {
                return this.createOn; 
            } 
            set 
            {
                this.createOn = value;
                onPropertyChanged("CreateOn");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("updateOn")]
        public string UpdateOn 
        { 
            get 
            {
                return this.updateOn; 
            } 
            set 
            {
                this.updateOn = value;
                onPropertyChanged("UpdateOn");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("createdBy")]
        public string CreatedBy 
        { 
            get 
            {
                return this.createdBy; 
            } 
            set 
            {
                this.createdBy = value;
                onPropertyChanged("CreatedBy");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("updatedBy")]
        public string UpdatedBy 
        { 
            get 
            {
                return this.updatedBy; 
            } 
            set 
            {
                this.updatedBy = value;
                onPropertyChanged("UpdatedBy");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("createOnPersianDate")]
        public string CreateOnPersianDate 
        { 
            get 
            {
                return this.createOnPersianDate; 
            } 
            set 
            {
                this.createOnPersianDate = value;
                onPropertyChanged("CreateOnPersianDate");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("updateOnPersianDate")]
        public string UpdateOnPersianDate 
        { 
            get 
            {
                return this.updateOnPersianDate; 
            } 
            set 
            {
                this.updateOnPersianDate = value;
                onPropertyChanged("UpdateOnPersianDate");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("deviceTypeTitle")]
        public string DeviceTypeTitle 
        { 
            get 
            {
                return this.deviceTypeTitle; 
            } 
            set 
            {
                this.deviceTypeTitle = value;
                onPropertyChanged("DeviceTypeTitle");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("deviceBrandTitle")]
        public string DeviceBrandTitle 
        { 
            get 
            {
                return this.deviceBrandTitle; 
            } 
            set 
            {
                this.deviceBrandTitle = value;
                onPropertyChanged("DeviceBrandTitle");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("deviceTypeBrandModelTitle")]
        public string DeviceTypeBrandModelTitle 
        { 
            get 
            {
                return this.deviceTypeBrandModelTitle; 
            } 
            set 
            {
                this.deviceTypeBrandModelTitle = value;
                onPropertyChanged("DeviceTypeBrandModelTitle");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("deviceBrandIds")]
        public List<string> DeviceBrandIds 
        { 
            get 
            {
                return this.deviceBrandIds; 
            } 
            set 
            {
                this.deviceBrandIds = value;
                onPropertyChanged("DeviceBrandIds");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("deviceBrandsTitle")]
        public string DeviceBrandsTitle 
        { 
            get 
            {
                return this.deviceBrandsTitle; 
            } 
            set 
            {
                this.deviceBrandsTitle = value;
                onPropertyChanged("DeviceBrandsTitle");
            }
        }
    }
} 