/*
 * EasyBimehLanding.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using EasyBimehLanding.Standard;
using EasyBimehLanding.Standard.Utilities;


namespace EasyBimehLanding.Standard.Models
{
    public class Earthquake : BaseModel 
    {
        // These fields hold the values for the public properties.
        private bool hasPlan;
        private int insuranceCentreProvinceId;
        private int insuranceCentreCityId;
        private List<Models.ComboDataModel> insuranceCentreCities;
        private List<Models.ComboDataModel> buildingTypes;
        private List<Models.ComboDataModel> skeletonTypeBuildings;
        private List<Models.ComboDataModel> buildingUseTypes;
        private List<Models.InsurancePolicyTerm> insurancePolicyTerms;
        private List<string> insuranceExtraCoverage;
        private List<Models.EverySquareMeterCoverage> everySquareMeterCoverage;
        private List<Models.Province> provinces;
        private List<string> cities;
        private List<string> cityRegions;
        private List<Models.ShippingType> shippingTypes;
        private List<Models.PostType> postTypes;
        private Models.InsurancePolicyCondition insurancePolicyCondition;
        private Models.InsuranceDataFireInsurance insuranceData;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("hasPlan")]
        public bool HasPlan 
        { 
            get 
            {
                return this.hasPlan; 
            } 
            set 
            {
                this.hasPlan = value;
                onPropertyChanged("HasPlan");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insuranceCentreProvinceId")]
        public int InsuranceCentreProvinceId 
        { 
            get 
            {
                return this.insuranceCentreProvinceId; 
            } 
            set 
            {
                this.insuranceCentreProvinceId = value;
                onPropertyChanged("InsuranceCentreProvinceId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insuranceCentreCityId")]
        public int InsuranceCentreCityId 
        { 
            get 
            {
                return this.insuranceCentreCityId; 
            } 
            set 
            {
                this.insuranceCentreCityId = value;
                onPropertyChanged("InsuranceCentreCityId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insuranceCentreCities")]
        public List<Models.ComboDataModel> InsuranceCentreCities 
        { 
            get 
            {
                return this.insuranceCentreCities; 
            } 
            set 
            {
                this.insuranceCentreCities = value;
                onPropertyChanged("InsuranceCentreCities");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("buildingTypes")]
        public List<Models.ComboDataModel> BuildingTypes 
        { 
            get 
            {
                return this.buildingTypes; 
            } 
            set 
            {
                this.buildingTypes = value;
                onPropertyChanged("BuildingTypes");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("skeletonTypeBuildings")]
        public List<Models.ComboDataModel> SkeletonTypeBuildings 
        { 
            get 
            {
                return this.skeletonTypeBuildings; 
            } 
            set 
            {
                this.skeletonTypeBuildings = value;
                onPropertyChanged("SkeletonTypeBuildings");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("buildingUseTypes")]
        public List<Models.ComboDataModel> BuildingUseTypes 
        { 
            get 
            {
                return this.buildingUseTypes; 
            } 
            set 
            {
                this.buildingUseTypes = value;
                onPropertyChanged("BuildingUseTypes");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insurancePolicyTerms")]
        public List<Models.InsurancePolicyTerm> InsurancePolicyTerms 
        { 
            get 
            {
                return this.insurancePolicyTerms; 
            } 
            set 
            {
                this.insurancePolicyTerms = value;
                onPropertyChanged("InsurancePolicyTerms");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insuranceExtraCoverage")]
        public List<string> InsuranceExtraCoverage 
        { 
            get 
            {
                return this.insuranceExtraCoverage; 
            } 
            set 
            {
                this.insuranceExtraCoverage = value;
                onPropertyChanged("InsuranceExtraCoverage");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("everySquareMeterCoverage")]
        public List<Models.EverySquareMeterCoverage> EverySquareMeterCoverage 
        { 
            get 
            {
                return this.everySquareMeterCoverage; 
            } 
            set 
            {
                this.everySquareMeterCoverage = value;
                onPropertyChanged("EverySquareMeterCoverage");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("provinces")]
        public List<Models.Province> Provinces 
        { 
            get 
            {
                return this.provinces; 
            } 
            set 
            {
                this.provinces = value;
                onPropertyChanged("Provinces");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("cities")]
        public List<string> Cities 
        { 
            get 
            {
                return this.cities; 
            } 
            set 
            {
                this.cities = value;
                onPropertyChanged("Cities");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("cityRegions")]
        public List<string> CityRegions 
        { 
            get 
            {
                return this.cityRegions; 
            } 
            set 
            {
                this.cityRegions = value;
                onPropertyChanged("CityRegions");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("shippingTypes")]
        public List<Models.ShippingType> ShippingTypes 
        { 
            get 
            {
                return this.shippingTypes; 
            } 
            set 
            {
                this.shippingTypes = value;
                onPropertyChanged("ShippingTypes");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("postTypes")]
        public List<Models.PostType> PostTypes 
        { 
            get 
            {
                return this.postTypes; 
            } 
            set 
            {
                this.postTypes = value;
                onPropertyChanged("PostTypes");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insurancePolicyCondition")]
        public Models.InsurancePolicyCondition InsurancePolicyCondition 
        { 
            get 
            {
                return this.insurancePolicyCondition; 
            } 
            set 
            {
                this.insurancePolicyCondition = value;
                onPropertyChanged("InsurancePolicyCondition");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insuranceData")]
        public Models.InsuranceDataFireInsurance InsuranceData 
        { 
            get 
            {
                return this.insuranceData; 
            } 
            set 
            {
                this.insuranceData = value;
                onPropertyChanged("InsuranceData");
            }
        }
    }
} 