/*
 * EasyBimehLanding.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using EasyBimehLanding.Standard;
using EasyBimehLanding.Standard.Utilities;


namespace EasyBimehLanding.Standard.Models
{
    public class ElectronicEquipmentInsurancePolicyExtendView : BaseModel 
    {
        // These fields hold the values for the public properties.
        private int? deviceTypeId;
        private int? deviceBrandId;
        private int? deviceModelId;
        private string deviceSerial;
        private string buildYear;
        private int? deviceValue;
        private int? franchisee;
        private bool? hasWarranty;
        private string warrantyCompany;
        private string serialInsuranceCard;
        private long? metaMediaBehindDeviceId;
        private string metaMediaBehindDeviceUrl;
        private long? metaMediaOnDeviceId;
        private string metaMediaOnDeviceUrl;
        private long? metaMediaDeviceBoxId;
        private string metaMediaDeviceBoxUrl;
        private string insuranceCoverageIds;
        private string insuranceCoveragePrice;
        private string basePremium;
        private string allPremium;
        private string insuranceCompanyDiscountRate;
        private int insuranceCompanyDiscount;
        private int insuranceCentreDiscount;
        private int coupenDiscount;
        private int allDiscount;
        private int exchangePremium;
        private string deviceTypeTitle;
        private string deviceBrandTitle;
        private string deviceModelTitle;

        /// <summary>
        /// شناسه ی نوع دستگاه
        /// </summary>
        [JsonProperty("deviceTypeId")]
        public int? DeviceTypeId 
        { 
            get 
            {
                return this.deviceTypeId; 
            } 
            set 
            {
                this.deviceTypeId = value;
                onPropertyChanged("DeviceTypeId");
            }
        }

        /// <summary>
        /// شناسه ی برند دستگاه
        /// </summary>
        [JsonProperty("deviceBrandId")]
        public int? DeviceBrandId 
        { 
            get 
            {
                return this.deviceBrandId; 
            } 
            set 
            {
                this.deviceBrandId = value;
                onPropertyChanged("DeviceBrandId");
            }
        }

        /// <summary>
        /// شناسه ی مدل دستگاه
        /// </summary>
        [JsonProperty("deviceModelId")]
        public int? DeviceModelId 
        { 
            get 
            {
                return this.deviceModelId; 
            } 
            set 
            {
                this.deviceModelId = value;
                onPropertyChanged("DeviceModelId");
            }
        }

        /// <summary>
        /// سریال دستگاه
        /// </summary>
        [JsonProperty("deviceSerial")]
        public string DeviceSerial 
        { 
            get 
            {
                return this.deviceSerial; 
            } 
            set 
            {
                this.deviceSerial = value;
                onPropertyChanged("DeviceSerial");
            }
        }

        /// <summary>
        /// سال ساخت دستگاه
        /// </summary>
        [JsonProperty("buildYear")]
        public string BuildYear 
        { 
            get 
            {
                return this.buildYear; 
            } 
            set 
            {
                this.buildYear = value;
                onPropertyChanged("BuildYear");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("deviceValue")]
        public int? DeviceValue 
        { 
            get 
            {
                return this.deviceValue; 
            } 
            set 
            {
                this.deviceValue = value;
                onPropertyChanged("DeviceValue");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("franchisee")]
        public int? Franchisee 
        { 
            get 
            {
                return this.franchisee; 
            } 
            set 
            {
                this.franchisee = value;
                onPropertyChanged("Franchisee");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("hasWarranty")]
        public bool? HasWarranty 
        { 
            get 
            {
                return this.hasWarranty; 
            } 
            set 
            {
                this.hasWarranty = value;
                onPropertyChanged("HasWarranty");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("warrantyCompany")]
        public string WarrantyCompany 
        { 
            get 
            {
                return this.warrantyCompany; 
            } 
            set 
            {
                this.warrantyCompany = value;
                onPropertyChanged("WarrantyCompany");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("serialInsuranceCard")]
        public string SerialInsuranceCard 
        { 
            get 
            {
                return this.serialInsuranceCard; 
            } 
            set 
            {
                this.serialInsuranceCard = value;
                onPropertyChanged("SerialInsuranceCard");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("metaMediaBehindDeviceId")]
        public long? MetaMediaBehindDeviceId 
        { 
            get 
            {
                return this.metaMediaBehindDeviceId; 
            } 
            set 
            {
                this.metaMediaBehindDeviceId = value;
                onPropertyChanged("MetaMediaBehindDeviceId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("metaMediaBehindDeviceUrl")]
        public string MetaMediaBehindDeviceUrl 
        { 
            get 
            {
                return this.metaMediaBehindDeviceUrl; 
            } 
            set 
            {
                this.metaMediaBehindDeviceUrl = value;
                onPropertyChanged("MetaMediaBehindDeviceUrl");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("metaMediaOnDeviceId")]
        public long? MetaMediaOnDeviceId 
        { 
            get 
            {
                return this.metaMediaOnDeviceId; 
            } 
            set 
            {
                this.metaMediaOnDeviceId = value;
                onPropertyChanged("MetaMediaOnDeviceId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("metaMediaOnDeviceUrl")]
        public string MetaMediaOnDeviceUrl 
        { 
            get 
            {
                return this.metaMediaOnDeviceUrl; 
            } 
            set 
            {
                this.metaMediaOnDeviceUrl = value;
                onPropertyChanged("MetaMediaOnDeviceUrl");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("metaMediaDeviceBoxId")]
        public long? MetaMediaDeviceBoxId 
        { 
            get 
            {
                return this.metaMediaDeviceBoxId; 
            } 
            set 
            {
                this.metaMediaDeviceBoxId = value;
                onPropertyChanged("MetaMediaDeviceBoxId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("metaMediaDeviceBoxUrl")]
        public string MetaMediaDeviceBoxUrl 
        { 
            get 
            {
                return this.metaMediaDeviceBoxUrl; 
            } 
            set 
            {
                this.metaMediaDeviceBoxUrl = value;
                onPropertyChanged("MetaMediaDeviceBoxUrl");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("_InsuranceCoverageIds")]
        public string InsuranceCoverageIds 
        { 
            get 
            {
                return this.insuranceCoverageIds; 
            } 
            set 
            {
                this.insuranceCoverageIds = value;
                onPropertyChanged("InsuranceCoverageIds");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insuranceCoveragePrice")]
        public string InsuranceCoveragePrice 
        { 
            get 
            {
                return this.insuranceCoveragePrice; 
            } 
            set 
            {
                this.insuranceCoveragePrice = value;
                onPropertyChanged("InsuranceCoveragePrice");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("basePremium")]
        public string BasePremium 
        { 
            get 
            {
                return this.basePremium; 
            } 
            set 
            {
                this.basePremium = value;
                onPropertyChanged("BasePremium");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("allPremium")]
        public string AllPremium 
        { 
            get 
            {
                return this.allPremium; 
            } 
            set 
            {
                this.allPremium = value;
                onPropertyChanged("AllPremium");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insuranceCompanyDiscountRate")]
        public string InsuranceCompanyDiscountRate 
        { 
            get 
            {
                return this.insuranceCompanyDiscountRate; 
            } 
            set 
            {
                this.insuranceCompanyDiscountRate = value;
                onPropertyChanged("InsuranceCompanyDiscountRate");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insuranceCompanyDiscount")]
        public int InsuranceCompanyDiscount 
        { 
            get 
            {
                return this.insuranceCompanyDiscount; 
            } 
            set 
            {
                this.insuranceCompanyDiscount = value;
                onPropertyChanged("InsuranceCompanyDiscount");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insuranceCentreDiscount")]
        public int InsuranceCentreDiscount 
        { 
            get 
            {
                return this.insuranceCentreDiscount; 
            } 
            set 
            {
                this.insuranceCentreDiscount = value;
                onPropertyChanged("InsuranceCentreDiscount");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("coupenDiscount")]
        public int CoupenDiscount 
        { 
            get 
            {
                return this.coupenDiscount; 
            } 
            set 
            {
                this.coupenDiscount = value;
                onPropertyChanged("CoupenDiscount");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("allDiscount")]
        public int AllDiscount 
        { 
            get 
            {
                return this.allDiscount; 
            } 
            set 
            {
                this.allDiscount = value;
                onPropertyChanged("AllDiscount");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("exchangePremium")]
        public int ExchangePremium 
        { 
            get 
            {
                return this.exchangePremium; 
            } 
            set 
            {
                this.exchangePremium = value;
                onPropertyChanged("ExchangePremium");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("deviceTypeTitle")]
        public string DeviceTypeTitle 
        { 
            get 
            {
                return this.deviceTypeTitle; 
            } 
            set 
            {
                this.deviceTypeTitle = value;
                onPropertyChanged("DeviceTypeTitle");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("deviceBrandTitle")]
        public string DeviceBrandTitle 
        { 
            get 
            {
                return this.deviceBrandTitle; 
            } 
            set 
            {
                this.deviceBrandTitle = value;
                onPropertyChanged("DeviceBrandTitle");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("deviceModelTitle")]
        public string DeviceModelTitle 
        { 
            get 
            {
                return this.deviceModelTitle; 
            } 
            set 
            {
                this.deviceModelTitle = value;
                onPropertyChanged("DeviceModelTitle");
            }
        }
    }
} 