/*
 * EasyBimehLanding.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using EasyBimehLanding.Standard;
using EasyBimehLanding.Standard.Utilities;


namespace EasyBimehLanding.Standard.Models
{
    public class ElevatorInsurancePolicyExtendView : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string buildingUseTypeParamId;
        private string elevatorTypeParamId;
        private string floors;
        private string elevatorCapacity;
        private string elevatorCapacityCargo;
        private string defectOrganCoverageId;
        private string deathCapitalCoverageId;
        private string financialCoverageId;
        private string medicalCostCoverageId;
        private string riskLevelDiscountRate;
        private string insuranceRiskLevelId;
        private string discountRate;
        private string cityId;
        private string provinceId;
        private string zipCode;
        private string addressPlaceBuilding;
        private bool ownerCoverage;
        private int riskLevelDiscount;
        private string basePremium;
        private string allPremium;
        private int insuranceCompanyDiscountRate;
        private int insuranceCompanyDiscount;
        private int insuranceCentreDiscount;
        private int coupenDiscount;
        private int allDiscount;
        private int exchangePremium;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("buildingUseTypeParamId")]
        public string BuildingUseTypeParamId 
        { 
            get 
            {
                return this.buildingUseTypeParamId; 
            } 
            set 
            {
                this.buildingUseTypeParamId = value;
                onPropertyChanged("BuildingUseTypeParamId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("elevatorTypeParamId")]
        public string ElevatorTypeParamId 
        { 
            get 
            {
                return this.elevatorTypeParamId; 
            } 
            set 
            {
                this.elevatorTypeParamId = value;
                onPropertyChanged("ElevatorTypeParamId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("floors")]
        public string Floors 
        { 
            get 
            {
                return this.floors; 
            } 
            set 
            {
                this.floors = value;
                onPropertyChanged("Floors");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("elevatorCapacity")]
        public string ElevatorCapacity 
        { 
            get 
            {
                return this.elevatorCapacity; 
            } 
            set 
            {
                this.elevatorCapacity = value;
                onPropertyChanged("ElevatorCapacity");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("elevatorCapacityCargo")]
        public string ElevatorCapacityCargo 
        { 
            get 
            {
                return this.elevatorCapacityCargo; 
            } 
            set 
            {
                this.elevatorCapacityCargo = value;
                onPropertyChanged("ElevatorCapacityCargo");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("defectOrganCoverageId")]
        public string DefectOrganCoverageId 
        { 
            get 
            {
                return this.defectOrganCoverageId; 
            } 
            set 
            {
                this.defectOrganCoverageId = value;
                onPropertyChanged("DefectOrganCoverageId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("deathCapitalCoverageId")]
        public string DeathCapitalCoverageId 
        { 
            get 
            {
                return this.deathCapitalCoverageId; 
            } 
            set 
            {
                this.deathCapitalCoverageId = value;
                onPropertyChanged("DeathCapitalCoverageId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("financialCoverageId")]
        public string FinancialCoverageId 
        { 
            get 
            {
                return this.financialCoverageId; 
            } 
            set 
            {
                this.financialCoverageId = value;
                onPropertyChanged("FinancialCoverageId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("medicalCostCoverageId")]
        public string MedicalCostCoverageId 
        { 
            get 
            {
                return this.medicalCostCoverageId; 
            } 
            set 
            {
                this.medicalCostCoverageId = value;
                onPropertyChanged("MedicalCostCoverageId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("riskLevelDiscountRate")]
        public string RiskLevelDiscountRate 
        { 
            get 
            {
                return this.riskLevelDiscountRate; 
            } 
            set 
            {
                this.riskLevelDiscountRate = value;
                onPropertyChanged("RiskLevelDiscountRate");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insuranceRiskLevelId")]
        public string InsuranceRiskLevelId 
        { 
            get 
            {
                return this.insuranceRiskLevelId; 
            } 
            set 
            {
                this.insuranceRiskLevelId = value;
                onPropertyChanged("InsuranceRiskLevelId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("discountRate")]
        public string DiscountRate 
        { 
            get 
            {
                return this.discountRate; 
            } 
            set 
            {
                this.discountRate = value;
                onPropertyChanged("DiscountRate");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("cityId")]
        public string CityId 
        { 
            get 
            {
                return this.cityId; 
            } 
            set 
            {
                this.cityId = value;
                onPropertyChanged("CityId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("provinceId")]
        public string ProvinceId 
        { 
            get 
            {
                return this.provinceId; 
            } 
            set 
            {
                this.provinceId = value;
                onPropertyChanged("ProvinceId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("zipCode")]
        public string ZipCode 
        { 
            get 
            {
                return this.zipCode; 
            } 
            set 
            {
                this.zipCode = value;
                onPropertyChanged("ZipCode");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("addressPlaceBuilding")]
        public string AddressPlaceBuilding 
        { 
            get 
            {
                return this.addressPlaceBuilding; 
            } 
            set 
            {
                this.addressPlaceBuilding = value;
                onPropertyChanged("AddressPlaceBuilding");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ownerCoverage")]
        public bool OwnerCoverage 
        { 
            get 
            {
                return this.ownerCoverage; 
            } 
            set 
            {
                this.ownerCoverage = value;
                onPropertyChanged("OwnerCoverage");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("riskLevelDiscount")]
        public int RiskLevelDiscount 
        { 
            get 
            {
                return this.riskLevelDiscount; 
            } 
            set 
            {
                this.riskLevelDiscount = value;
                onPropertyChanged("RiskLevelDiscount");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("basePremium")]
        public string BasePremium 
        { 
            get 
            {
                return this.basePremium; 
            } 
            set 
            {
                this.basePremium = value;
                onPropertyChanged("BasePremium");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("allPremium")]
        public string AllPremium 
        { 
            get 
            {
                return this.allPremium; 
            } 
            set 
            {
                this.allPremium = value;
                onPropertyChanged("AllPremium");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insuranceCompanyDiscountRate")]
        public int InsuranceCompanyDiscountRate 
        { 
            get 
            {
                return this.insuranceCompanyDiscountRate; 
            } 
            set 
            {
                this.insuranceCompanyDiscountRate = value;
                onPropertyChanged("InsuranceCompanyDiscountRate");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insuranceCompanyDiscount")]
        public int InsuranceCompanyDiscount 
        { 
            get 
            {
                return this.insuranceCompanyDiscount; 
            } 
            set 
            {
                this.insuranceCompanyDiscount = value;
                onPropertyChanged("InsuranceCompanyDiscount");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insuranceCentreDiscount")]
        public int InsuranceCentreDiscount 
        { 
            get 
            {
                return this.insuranceCentreDiscount; 
            } 
            set 
            {
                this.insuranceCentreDiscount = value;
                onPropertyChanged("InsuranceCentreDiscount");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("coupenDiscount")]
        public int CoupenDiscount 
        { 
            get 
            {
                return this.coupenDiscount; 
            } 
            set 
            {
                this.coupenDiscount = value;
                onPropertyChanged("CoupenDiscount");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("allDiscount")]
        public int AllDiscount 
        { 
            get 
            {
                return this.allDiscount; 
            } 
            set 
            {
                this.allDiscount = value;
                onPropertyChanged("AllDiscount");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("exchangePremium")]
        public int ExchangePremium 
        { 
            get 
            {
                return this.exchangePremium; 
            } 
            set 
            {
                this.exchangePremium = value;
                onPropertyChanged("ExchangePremium");
            }
        }
    }
} 