/*
 * EasyBimehLanding.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using EasyBimehLanding.Standard;
using EasyBimehLanding.Standard.Utilities;


namespace EasyBimehLanding.Standard.Models
{
    public class ElevatorInsurance : BaseModel 
    {
        // These fields hold the values for the public properties.
        private bool hasPlan;
        private List<Models.ComboDataModel> buildingUseTypes;
        private List<Models.ElevatorType> elevatorTypes;
        private List<Models.DefectOrganCoverage> defectOrganCoverage;
        private List<Models.DeathCapitalCoverage> deathCapitalCoverage;
        private List<Models.FinancialCoverage> financialCoverage;
        private List<Models.MedicalCostCoverage> medicalCostCoverage;
        private List<Models.InsuranceRiskLevel> insuranceRiskLevels;
        private List<Models.InsurancePolicyTerm> insurancePolicyTerms;
        private List<Models.InsuranceCompany> insuranceCompanies;
        private List<Models.Province> provinces;
        private List<string> cities;
        private List<string> cityRegions;
        private List<Models.ShippingType> shippingTypes;
        private List<Models.PostType> postTypes;
        private Models.InsurancePolicyCondition insurancePolicyCondition;
        private Models.InsuranceDataElevatorInsurance insuranceData;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("hasPlan")]
        public bool HasPlan 
        { 
            get 
            {
                return this.hasPlan; 
            } 
            set 
            {
                this.hasPlan = value;
                onPropertyChanged("HasPlan");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("buildingUseTypes")]
        public List<Models.ComboDataModel> BuildingUseTypes 
        { 
            get 
            {
                return this.buildingUseTypes; 
            } 
            set 
            {
                this.buildingUseTypes = value;
                onPropertyChanged("BuildingUseTypes");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("elevatorTypes")]
        public List<Models.ElevatorType> ElevatorTypes 
        { 
            get 
            {
                return this.elevatorTypes; 
            } 
            set 
            {
                this.elevatorTypes = value;
                onPropertyChanged("ElevatorTypes");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("defectOrganCoverage")]
        public List<Models.DefectOrganCoverage> DefectOrganCoverage 
        { 
            get 
            {
                return this.defectOrganCoverage; 
            } 
            set 
            {
                this.defectOrganCoverage = value;
                onPropertyChanged("DefectOrganCoverage");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("deathCapitalCoverage")]
        public List<Models.DeathCapitalCoverage> DeathCapitalCoverage 
        { 
            get 
            {
                return this.deathCapitalCoverage; 
            } 
            set 
            {
                this.deathCapitalCoverage = value;
                onPropertyChanged("DeathCapitalCoverage");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("financialCoverage")]
        public List<Models.FinancialCoverage> FinancialCoverage 
        { 
            get 
            {
                return this.financialCoverage; 
            } 
            set 
            {
                this.financialCoverage = value;
                onPropertyChanged("FinancialCoverage");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("medicalCostCoverage")]
        public List<Models.MedicalCostCoverage> MedicalCostCoverage 
        { 
            get 
            {
                return this.medicalCostCoverage; 
            } 
            set 
            {
                this.medicalCostCoverage = value;
                onPropertyChanged("MedicalCostCoverage");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insuranceRiskLevels")]
        public List<Models.InsuranceRiskLevel> InsuranceRiskLevels 
        { 
            get 
            {
                return this.insuranceRiskLevels; 
            } 
            set 
            {
                this.insuranceRiskLevels = value;
                onPropertyChanged("InsuranceRiskLevels");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insurancePolicyTerms")]
        public List<Models.InsurancePolicyTerm> InsurancePolicyTerms 
        { 
            get 
            {
                return this.insurancePolicyTerms; 
            } 
            set 
            {
                this.insurancePolicyTerms = value;
                onPropertyChanged("InsurancePolicyTerms");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insuranceCompanies")]
        public List<Models.InsuranceCompany> InsuranceCompanies 
        { 
            get 
            {
                return this.insuranceCompanies; 
            } 
            set 
            {
                this.insuranceCompanies = value;
                onPropertyChanged("InsuranceCompanies");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("provinces")]
        public List<Models.Province> Provinces 
        { 
            get 
            {
                return this.provinces; 
            } 
            set 
            {
                this.provinces = value;
                onPropertyChanged("Provinces");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("cities")]
        public List<string> Cities 
        { 
            get 
            {
                return this.cities; 
            } 
            set 
            {
                this.cities = value;
                onPropertyChanged("Cities");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("cityRegions")]
        public List<string> CityRegions 
        { 
            get 
            {
                return this.cityRegions; 
            } 
            set 
            {
                this.cityRegions = value;
                onPropertyChanged("CityRegions");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("shippingTypes")]
        public List<Models.ShippingType> ShippingTypes 
        { 
            get 
            {
                return this.shippingTypes; 
            } 
            set 
            {
                this.shippingTypes = value;
                onPropertyChanged("ShippingTypes");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("postTypes")]
        public List<Models.PostType> PostTypes 
        { 
            get 
            {
                return this.postTypes; 
            } 
            set 
            {
                this.postTypes = value;
                onPropertyChanged("PostTypes");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insurancePolicyCondition")]
        public Models.InsurancePolicyCondition InsurancePolicyCondition 
        { 
            get 
            {
                return this.insurancePolicyCondition; 
            } 
            set 
            {
                this.insurancePolicyCondition = value;
                onPropertyChanged("InsurancePolicyCondition");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insuranceData")]
        public Models.InsuranceDataElevatorInsurance InsuranceData 
        { 
            get 
            {
                return this.insuranceData; 
            } 
            set 
            {
                this.insuranceData = value;
                onPropertyChanged("InsuranceData");
            }
        }
    }
} 