/*
 * EasyBimehLanding.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using EasyBimehLanding.Standard;
using EasyBimehLanding.Standard.Utilities;


namespace EasyBimehLanding.Standard.Models
{
    public class ExtraDataBaseModelInsuranceCentrePolicyTypes : BaseModel 
    {
        // These fields hold the values for the public properties.
        private int insuranceTypesCount;
        private bool hasPlan;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insuranceTypesCount")]
        public int InsuranceTypesCount 
        { 
            get 
            {
                return this.insuranceTypesCount; 
            } 
            set 
            {
                this.insuranceTypesCount = value;
                onPropertyChanged("InsuranceTypesCount");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("hasPlan")]
        public bool HasPlan 
        { 
            get 
            {
                return this.hasPlan; 
            } 
            set 
            {
                this.hasPlan = value;
                onPropertyChanged("HasPlan");
            }
        }
    }
} 