/*
 * EasyBimehLanding.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using EasyBimehLanding.Standard;
using EasyBimehLanding.Standard.Utilities;


namespace EasyBimehLanding.Standard.Models
{
    public class FireInsurancePolicyFilter : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string insurancePolicyType;
        private string insuranceExtraCoverageIds;
        private string valuePerSquareMeterCoverageRateId;
        private string valueOfAppliancesFurnishing;
        private string cityId;
        private string skeletonTypeId;
        private int buildingTypeId;
        private string buildingArea;
        private string onlyAppliancesFurnishings;
        private string policyTermId;
        private string insuranceCentreSubDomainName;
        private string insuranceCentreId;
        private string insuranceCompanyId;
        private string giftCode;
        private string customerUserId;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insurancePolicyType")]
        public string InsurancePolicyType 
        { 
            get 
            {
                return this.insurancePolicyType; 
            } 
            set 
            {
                this.insurancePolicyType = value;
                onPropertyChanged("InsurancePolicyType");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insuranceExtraCoverageIds")]
        public string InsuranceExtraCoverageIds 
        { 
            get 
            {
                return this.insuranceExtraCoverageIds; 
            } 
            set 
            {
                this.insuranceExtraCoverageIds = value;
                onPropertyChanged("InsuranceExtraCoverageIds");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("valuePerSquareMeterCoverageRateId")]
        public string ValuePerSquareMeterCoverageRateId 
        { 
            get 
            {
                return this.valuePerSquareMeterCoverageRateId; 
            } 
            set 
            {
                this.valuePerSquareMeterCoverageRateId = value;
                onPropertyChanged("ValuePerSquareMeterCoverageRateId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("valueOfAppliancesFurnishing")]
        public string ValueOfAppliancesFurnishing 
        { 
            get 
            {
                return this.valueOfAppliancesFurnishing; 
            } 
            set 
            {
                this.valueOfAppliancesFurnishing = value;
                onPropertyChanged("ValueOfAppliancesFurnishing");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("cityId")]
        public string CityId 
        { 
            get 
            {
                return this.cityId; 
            } 
            set 
            {
                this.cityId = value;
                onPropertyChanged("CityId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("skeletonTypeId")]
        public string SkeletonTypeId 
        { 
            get 
            {
                return this.skeletonTypeId; 
            } 
            set 
            {
                this.skeletonTypeId = value;
                onPropertyChanged("SkeletonTypeId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("buildingTypeId")]
        public int BuildingTypeId 
        { 
            get 
            {
                return this.buildingTypeId; 
            } 
            set 
            {
                this.buildingTypeId = value;
                onPropertyChanged("BuildingTypeId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("buildingArea")]
        public string BuildingArea 
        { 
            get 
            {
                return this.buildingArea; 
            } 
            set 
            {
                this.buildingArea = value;
                onPropertyChanged("BuildingArea");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("onlyAppliancesFurnishings")]
        public string OnlyAppliancesFurnishings 
        { 
            get 
            {
                return this.onlyAppliancesFurnishings; 
            } 
            set 
            {
                this.onlyAppliancesFurnishings = value;
                onPropertyChanged("OnlyAppliancesFurnishings");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("policyTermId")]
        public string PolicyTermId 
        { 
            get 
            {
                return this.policyTermId; 
            } 
            set 
            {
                this.policyTermId = value;
                onPropertyChanged("PolicyTermId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insuranceCentreSubDomainName")]
        public string InsuranceCentreSubDomainName 
        { 
            get 
            {
                return this.insuranceCentreSubDomainName; 
            } 
            set 
            {
                this.insuranceCentreSubDomainName = value;
                onPropertyChanged("InsuranceCentreSubDomainName");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insuranceCentreId")]
        public string InsuranceCentreId 
        { 
            get 
            {
                return this.insuranceCentreId; 
            } 
            set 
            {
                this.insuranceCentreId = value;
                onPropertyChanged("InsuranceCentreId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insuranceCompanyId")]
        public string InsuranceCompanyId 
        { 
            get 
            {
                return this.insuranceCompanyId; 
            } 
            set 
            {
                this.insuranceCompanyId = value;
                onPropertyChanged("InsuranceCompanyId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("giftCode")]
        public string GiftCode 
        { 
            get 
            {
                return this.giftCode; 
            } 
            set 
            {
                this.giftCode = value;
                onPropertyChanged("GiftCode");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("customerUserId")]
        public string CustomerUserId 
        { 
            get 
            {
                return this.customerUserId; 
            } 
            set 
            {
                this.customerUserId = value;
                onPropertyChanged("CustomerUserId");
            }
        }
    }
} 