/*
 * EasyBimehLanding.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using EasyBimehLanding.Standard;
using EasyBimehLanding.Standard.Utilities;


namespace EasyBimehLanding.Standard.Models
{
    public class GalleryDetail : BaseModel 
    {
        // These fields hold the values for the public properties.
        private int galleryId;
        private int metaMediaFileId;
        private string metaMediaFileUrl;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("galleryId")]
        public int GalleryId 
        { 
            get 
            {
                return this.galleryId; 
            } 
            set 
            {
                this.galleryId = value;
                onPropertyChanged("GalleryId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("metaMediaFileId")]
        public int MetaMediaFileId 
        { 
            get 
            {
                return this.metaMediaFileId; 
            } 
            set 
            {
                this.metaMediaFileId = value;
                onPropertyChanged("MetaMediaFileId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("metaMediaFileUrl")]
        public string MetaMediaFileUrl 
        { 
            get 
            {
                return this.metaMediaFileUrl; 
            } 
            set 
            {
                this.metaMediaFileUrl = value;
                onPropertyChanged("MetaMediaFileUrl");
            }
        }
    }
} 