/*
 * EasyBimehLanding.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using EasyBimehLanding.Standard;
using EasyBimehLanding.Standard.Utilities;


namespace EasyBimehLanding.Standard.Models
{
    public class GetAccessTokenUserInfo : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string id;
        private string accessToken;
        private string expiresIn;
        private string refreshToken;
        private string error;
        private string userName;
        private string insuranceCentreName;
        private string insuranceCentreLogo;
        private string insuranceCentreFavicon;
        private bool licensed;
        private string email;
        private int insuranceCentreType;
        private string avatarUrl;
        private string aliasName;
        private int userGroup;
        private string userGroupTitle;
        private List<string> roleIds;
        private string roleTitles;
        private bool unlimitedAccount;
        private string rolePermissions;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("id")]
        public string Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("access_token")]
        public string AccessToken 
        { 
            get 
            {
                return this.accessToken; 
            } 
            set 
            {
                this.accessToken = value;
                onPropertyChanged("AccessToken");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("expires_in")]
        public string ExpiresIn 
        { 
            get 
            {
                return this.expiresIn; 
            } 
            set 
            {
                this.expiresIn = value;
                onPropertyChanged("ExpiresIn");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("refresh_token")]
        public string RefreshToken 
        { 
            get 
            {
                return this.refreshToken; 
            } 
            set 
            {
                this.refreshToken = value;
                onPropertyChanged("RefreshToken");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("error")]
        public string Error 
        { 
            get 
            {
                return this.error; 
            } 
            set 
            {
                this.error = value;
                onPropertyChanged("Error");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("userName")]
        public string UserName 
        { 
            get 
            {
                return this.userName; 
            } 
            set 
            {
                this.userName = value;
                onPropertyChanged("UserName");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insuranceCentreName")]
        public string InsuranceCentreName 
        { 
            get 
            {
                return this.insuranceCentreName; 
            } 
            set 
            {
                this.insuranceCentreName = value;
                onPropertyChanged("InsuranceCentreName");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insuranceCentreLogo")]
        public string InsuranceCentreLogo 
        { 
            get 
            {
                return this.insuranceCentreLogo; 
            } 
            set 
            {
                this.insuranceCentreLogo = value;
                onPropertyChanged("InsuranceCentreLogo");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insuranceCentreFavicon")]
        public string InsuranceCentreFavicon 
        { 
            get 
            {
                return this.insuranceCentreFavicon; 
            } 
            set 
            {
                this.insuranceCentreFavicon = value;
                onPropertyChanged("InsuranceCentreFavicon");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("licensed")]
        public bool Licensed 
        { 
            get 
            {
                return this.licensed; 
            } 
            set 
            {
                this.licensed = value;
                onPropertyChanged("Licensed");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("email")]
        public string Email 
        { 
            get 
            {
                return this.email; 
            } 
            set 
            {
                this.email = value;
                onPropertyChanged("Email");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insuranceCentreType")]
        public int InsuranceCentreType 
        { 
            get 
            {
                return this.insuranceCentreType; 
            } 
            set 
            {
                this.insuranceCentreType = value;
                onPropertyChanged("InsuranceCentreType");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("avatarUrl")]
        public string AvatarUrl 
        { 
            get 
            {
                return this.avatarUrl; 
            } 
            set 
            {
                this.avatarUrl = value;
                onPropertyChanged("AvatarUrl");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("aliasName")]
        public string AliasName 
        { 
            get 
            {
                return this.aliasName; 
            } 
            set 
            {
                this.aliasName = value;
                onPropertyChanged("AliasName");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("userGroup")]
        public int UserGroup 
        { 
            get 
            {
                return this.userGroup; 
            } 
            set 
            {
                this.userGroup = value;
                onPropertyChanged("UserGroup");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("userGroupTitle")]
        public string UserGroupTitle 
        { 
            get 
            {
                return this.userGroupTitle; 
            } 
            set 
            {
                this.userGroupTitle = value;
                onPropertyChanged("UserGroupTitle");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("roleIds")]
        public List<string> RoleIds 
        { 
            get 
            {
                return this.roleIds; 
            } 
            set 
            {
                this.roleIds = value;
                onPropertyChanged("RoleIds");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("roleTitles")]
        public string RoleTitles 
        { 
            get 
            {
                return this.roleTitles; 
            } 
            set 
            {
                this.roleTitles = value;
                onPropertyChanged("RoleTitles");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("unlimitedAccount")]
        public bool UnlimitedAccount 
        { 
            get 
            {
                return this.unlimitedAccount; 
            } 
            set 
            {
                this.unlimitedAccount = value;
                onPropertyChanged("UnlimitedAccount");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("rolePermissions")]
        public string RolePermissions 
        { 
            get 
            {
                return this.rolePermissions; 
            } 
            set 
            {
                this.rolePermissions = value;
                onPropertyChanged("RolePermissions");
            }
        }
    }
} 