/*
 * EasyBimehLanding.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using EasyBimehLanding.Standard;
using EasyBimehLanding.Standard.Utilities;


namespace EasyBimehLanding.Standard.Models
{
    public class InsurancePolicyTracking : BaseModel 
    {
        // These fields hold the values for the public properties.
        private int id;
        private string aliasName;
        private string status;
        private string createOnPersianDate;
        private string centerName;
        private int insurancePolicyType;
        private string insuranceType;
        private int price;
        private string paymented;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("id")]
        public int Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("aliasName")]
        public string AliasName 
        { 
            get 
            {
                return this.aliasName; 
            } 
            set 
            {
                this.aliasName = value;
                onPropertyChanged("AliasName");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("status")]
        public string Status 
        { 
            get 
            {
                return this.status; 
            } 
            set 
            {
                this.status = value;
                onPropertyChanged("Status");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("createOnPersianDate")]
        public string CreateOnPersianDate 
        { 
            get 
            {
                return this.createOnPersianDate; 
            } 
            set 
            {
                this.createOnPersianDate = value;
                onPropertyChanged("CreateOnPersianDate");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("centerName")]
        public string CenterName 
        { 
            get 
            {
                return this.centerName; 
            } 
            set 
            {
                this.centerName = value;
                onPropertyChanged("CenterName");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insurancePolicyType")]
        public int InsurancePolicyType 
        { 
            get 
            {
                return this.insurancePolicyType; 
            } 
            set 
            {
                this.insurancePolicyType = value;
                onPropertyChanged("InsurancePolicyType");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insuranceType")]
        public string InsuranceType 
        { 
            get 
            {
                return this.insuranceType; 
            } 
            set 
            {
                this.insuranceType = value;
                onPropertyChanged("InsuranceType");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("price")]
        public int Price 
        { 
            get 
            {
                return this.price; 
            } 
            set 
            {
                this.price = value;
                onPropertyChanged("Price");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("paymented")]
        public string Paymented 
        { 
            get 
            {
                return this.paymented; 
            } 
            set 
            {
                this.paymented = value;
                onPropertyChanged("Paymented");
            }
        }
    }
} 