/*
 * EasyBimehLanding.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using EasyBimehLanding.Standard;
using EasyBimehLanding.Standard.Utilities;


namespace EasyBimehLanding.Standard.Models
{
    public class InsuranceDataTravelInsurance : BaseModel 
    {
        // These fields hold the values for the public properties.
        private Models.TravelInsurancePolicyExtendView travelInsurancePolicyExtendView;
        private Models.TravelInsurancePolicyFilter travelInsurancePolicyFilter;
        private int id;
        private bool selectedInsurancePolicyHasBeenChanged;
        private bool isPaymented;
        private string payable;
        private string paymented;
        private string conflict;
        private bool hasConflictDocument;
        private string initialPrice;
        private string finalPrice;
        private string insuranceCompanyName;
        private string insuranceCentreName;
        private bool isInsuranceCentreAdmin;
        private List<string> insurancePolicyPaymentDocuments;
        private string insurancePolicyConflict;
        private string insurancePolicyCondition;
        private string person;
        private string insurancePolicy;
        private string shoppingCard;
        private string shoppingCardPostalPacket;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("travelInsurancePolicyExtendView")]
        public Models.TravelInsurancePolicyExtendView TravelInsurancePolicyExtendView 
        { 
            get 
            {
                return this.travelInsurancePolicyExtendView; 
            } 
            set 
            {
                this.travelInsurancePolicyExtendView = value;
                onPropertyChanged("TravelInsurancePolicyExtendView");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("travelInsurancePolicyFilter")]
        public Models.TravelInsurancePolicyFilter TravelInsurancePolicyFilter 
        { 
            get 
            {
                return this.travelInsurancePolicyFilter; 
            } 
            set 
            {
                this.travelInsurancePolicyFilter = value;
                onPropertyChanged("TravelInsurancePolicyFilter");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("id")]
        public int Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("selectedInsurancePolicyHasBeenChanged")]
        public bool SelectedInsurancePolicyHasBeenChanged 
        { 
            get 
            {
                return this.selectedInsurancePolicyHasBeenChanged; 
            } 
            set 
            {
                this.selectedInsurancePolicyHasBeenChanged = value;
                onPropertyChanged("SelectedInsurancePolicyHasBeenChanged");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("isPaymented")]
        public bool IsPaymented 
        { 
            get 
            {
                return this.isPaymented; 
            } 
            set 
            {
                this.isPaymented = value;
                onPropertyChanged("IsPaymented");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("payable")]
        public string Payable 
        { 
            get 
            {
                return this.payable; 
            } 
            set 
            {
                this.payable = value;
                onPropertyChanged("Payable");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("paymented")]
        public string Paymented 
        { 
            get 
            {
                return this.paymented; 
            } 
            set 
            {
                this.paymented = value;
                onPropertyChanged("Paymented");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("conflict")]
        public string Conflict 
        { 
            get 
            {
                return this.conflict; 
            } 
            set 
            {
                this.conflict = value;
                onPropertyChanged("Conflict");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("hasConflictDocument")]
        public bool HasConflictDocument 
        { 
            get 
            {
                return this.hasConflictDocument; 
            } 
            set 
            {
                this.hasConflictDocument = value;
                onPropertyChanged("HasConflictDocument");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("initialPrice")]
        public string InitialPrice 
        { 
            get 
            {
                return this.initialPrice; 
            } 
            set 
            {
                this.initialPrice = value;
                onPropertyChanged("InitialPrice");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("finalPrice")]
        public string FinalPrice 
        { 
            get 
            {
                return this.finalPrice; 
            } 
            set 
            {
                this.finalPrice = value;
                onPropertyChanged("FinalPrice");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insuranceCompanyName")]
        public string InsuranceCompanyName 
        { 
            get 
            {
                return this.insuranceCompanyName; 
            } 
            set 
            {
                this.insuranceCompanyName = value;
                onPropertyChanged("InsuranceCompanyName");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insuranceCentreName")]
        public string InsuranceCentreName 
        { 
            get 
            {
                return this.insuranceCentreName; 
            } 
            set 
            {
                this.insuranceCentreName = value;
                onPropertyChanged("InsuranceCentreName");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("isInsuranceCentreAdmin")]
        public bool IsInsuranceCentreAdmin 
        { 
            get 
            {
                return this.isInsuranceCentreAdmin; 
            } 
            set 
            {
                this.isInsuranceCentreAdmin = value;
                onPropertyChanged("IsInsuranceCentreAdmin");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insurancePolicyPaymentDocuments")]
        public List<string> InsurancePolicyPaymentDocuments 
        { 
            get 
            {
                return this.insurancePolicyPaymentDocuments; 
            } 
            set 
            {
                this.insurancePolicyPaymentDocuments = value;
                onPropertyChanged("InsurancePolicyPaymentDocuments");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insurancePolicyConflict")]
        public string InsurancePolicyConflict 
        { 
            get 
            {
                return this.insurancePolicyConflict; 
            } 
            set 
            {
                this.insurancePolicyConflict = value;
                onPropertyChanged("InsurancePolicyConflict");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insurancePolicyCondition")]
        public string InsurancePolicyCondition 
        { 
            get 
            {
                return this.insurancePolicyCondition; 
            } 
            set 
            {
                this.insurancePolicyCondition = value;
                onPropertyChanged("InsurancePolicyCondition");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("person")]
        public string Person 
        { 
            get 
            {
                return this.person; 
            } 
            set 
            {
                this.person = value;
                onPropertyChanged("Person");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insurancePolicy")]
        public string InsurancePolicy 
        { 
            get 
            {
                return this.insurancePolicy; 
            } 
            set 
            {
                this.insurancePolicy = value;
                onPropertyChanged("InsurancePolicy");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("shoppingCard")]
        public string ShoppingCard 
        { 
            get 
            {
                return this.shoppingCard; 
            } 
            set 
            {
                this.shoppingCard = value;
                onPropertyChanged("ShoppingCard");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("shoppingCardPostalPacket")]
        public string ShoppingCardPostalPacket 
        { 
            get 
            {
                return this.shoppingCardPostalPacket; 
            } 
            set 
            {
                this.shoppingCardPostalPacket = value;
                onPropertyChanged("ShoppingCardPostalPacket");
            }
        }
    }
} 