/*
 * EasyBimehLanding.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using EasyBimehLanding.Standard;
using EasyBimehLanding.Standard.Utilities;


namespace EasyBimehLanding.Standard.Models
{
    public class InsurancePolicyCondition : BaseModel 
    {
        // These fields hold the values for the public properties.
        private int id;
        private int insuranceCentreId;
        private int insuranceCompanyPolicyTypeId;
        private string displayPriority;
        private string issueInsurance;
        private string damageAssessment;
        private string cashPayment;
        private string installmentsPayment;
        private string prepaymentPercent;
        private string countInstallmentFrom;
        private string countInstallmentTo;
        private string paymentMethods;
        private string promotion;
        private bool isActive;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("id")]
        public int Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// شناسه ی مرکز بیمه
        /// </summary>
        [JsonProperty("insuranceCentreId")]
        public int InsuranceCentreId 
        { 
            get 
            {
                return this.insuranceCentreId; 
            } 
            set 
            {
                this.insuranceCentreId = value;
                onPropertyChanged("InsuranceCentreId");
            }
        }

        /// <summary>
        /// شناسه ی نوع بیمه نامه ی شرکت بیمه
        /// </summary>
        [JsonProperty("insuranceCompanyPolicyTypeId")]
        public int InsuranceCompanyPolicyTypeId 
        { 
            get 
            {
                return this.insuranceCompanyPolicyTypeId; 
            } 
            set 
            {
                this.insuranceCompanyPolicyTypeId = value;
                onPropertyChanged("InsuranceCompanyPolicyTypeId");
            }
        }

        /// <summary>
        /// الویت نمایش
        /// </summary>
        [JsonProperty("displayPriority")]
        public string DisplayPriority 
        { 
            get 
            {
                return this.displayPriority; 
            } 
            set 
            {
                this.displayPriority = value;
                onPropertyChanged("DisplayPriority");
            }
        }

        /// <summary>
        /// امکان صدور بیمه نامه
        /// </summary>
        [JsonProperty("issueInsurance")]
        public string IssueInsurance 
        { 
            get 
            {
                return this.issueInsurance; 
            } 
            set 
            {
                this.issueInsurance = value;
                onPropertyChanged("IssueInsurance");
            }
        }

        /// <summary>
        /// ارزیابی خسارت
        /// </summary>
        [JsonProperty("damageAssessment")]
        public string DamageAssessment 
        { 
            get 
            {
                return this.damageAssessment; 
            } 
            set 
            {
                this.damageAssessment = value;
                onPropertyChanged("DamageAssessment");
            }
        }

        /// <summary>
        /// پرداخت نقدی
        /// </summary>
        [JsonProperty("cashPayment")]
        public string CashPayment 
        { 
            get 
            {
                return this.cashPayment; 
            } 
            set 
            {
                this.cashPayment = value;
                onPropertyChanged("CashPayment");
            }
        }

        /// <summary>
        /// پرداخت اقساطی
        /// </summary>
        [JsonProperty("installmentsPayment")]
        public string InstallmentsPayment 
        { 
            get 
            {
                return this.installmentsPayment; 
            } 
            set 
            {
                this.installmentsPayment = value;
                onPropertyChanged("InstallmentsPayment");
            }
        }

        /// <summary>
        /// درصدر پیش پرداخت
        /// </summary>
        [JsonProperty("prepaymentPercent")]
        public string PrepaymentPercent 
        { 
            get 
            {
                return this.prepaymentPercent; 
            } 
            set 
            {
                this.prepaymentPercent = value;
                onPropertyChanged("PrepaymentPercent");
            }
        }

        /// <summary>
        /// تعداد اقساط از
        /// </summary>
        [JsonProperty("countInstallmentFrom")]
        public string CountInstallmentFrom 
        { 
            get 
            {
                return this.countInstallmentFrom; 
            } 
            set 
            {
                this.countInstallmentFrom = value;
                onPropertyChanged("CountInstallmentFrom");
            }
        }

        /// <summary>
        /// تعداد اقساط تا
        /// </summary>
        [JsonProperty("countInstallmentTo")]
        public string CountInstallmentTo 
        { 
            get 
            {
                return this.countInstallmentTo; 
            } 
            set 
            {
                this.countInstallmentTo = value;
                onPropertyChanged("CountInstallmentTo");
            }
        }

        /// <summary>
        /// روش فروش
        /// </summary>
        [JsonProperty("paymentMethods")]
        public string PaymentMethods 
        { 
            get 
            {
                return this.paymentMethods; 
            } 
            set 
            {
                this.paymentMethods = value;
                onPropertyChanged("PaymentMethods");
            }
        }

        /// <summary>
        /// پروموشن
        /// </summary>
        [JsonProperty("promotion")]
        public string Promotion 
        { 
            get 
            {
                return this.promotion; 
            } 
            set 
            {
                this.promotion = value;
                onPropertyChanged("Promotion");
            }
        }

        /// <summary>
        /// وضعیت فعال
        /// </summary>
        [JsonProperty("isActive")]
        public bool IsActive 
        { 
            get 
            {
                return this.isActive; 
            } 
            set 
            {
                this.isActive = value;
                onPropertyChanged("IsActive");
            }
        }
    }
} 