/*
 * EasyBimehLanding.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using EasyBimehLanding.Standard;
using EasyBimehLanding.Standard.Utilities;


namespace EasyBimehLanding.Standard.Models
{
    public class InsuranceExtraCoverageExtraData : BaseModel 
    {
        // These fields hold the values for the public properties.
        private bool defaultStatus;
        private bool requiringExpertVisit;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("defaultStatus")]
        public bool DefaultStatus 
        { 
            get 
            {
                return this.defaultStatus; 
            } 
            set 
            {
                this.defaultStatus = value;
                onPropertyChanged("DefaultStatus");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("requiringExpertVisit")]
        public bool RequiringExpertVisit 
        { 
            get 
            {
                return this.requiringExpertVisit; 
            } 
            set 
            {
                this.requiringExpertVisit = value;
                onPropertyChanged("RequiringExpertVisit");
            }
        }
    }
} 