/*
 * EasyBimehLanding.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using EasyBimehLanding.Standard;
using EasyBimehLanding.Standard.Utilities;


namespace EasyBimehLanding.Standard.Models
{
    public class InsuranceCentre : BaseModel 
    {
        // These fields hold the values for the public properties.
        private int id;
        private string personId;
        private int personalityType;
        private int insuranceCentreType;
        private int registerStatus;
        private string centerName;
        private string centerCode;
        private string branchCount;
        private string registrationNumber;
        private string freeUseGoldenPackExpireDate;
        private int cityId;
        private bool cashPayment;
        private bool showInEasyBimeh;
        private bool installmentsPayment;
        private bool isInitialApplicant;
        private int branchsCount;
        private int employeesCount;
        private string zoneId;
        private string smsChargingStock;
        private string independentBranch;
        private string disableReason;
        private string termsConditions;
        private string disableReasonDescription;
        private string unlimitedAccount;
        private bool whiteLabel;
        private string phone;
        private string fax;
        private string address;
        private string zipCode;
        private string email;
        private string paymentUrl;
        private string callbackUrl;
        private string callbackUrlWhitelabel;
        private string webSite;
        private double latitude;
        private double longitude;
        private bool isActive;
        private string insuranceCentreId;
        private string cityRegionId;
        private string provinceId;
        private string cityName;
        private int metaMediaActivityLicenceId;
        private string metaMediaActivityLicenceUrl;
        private string createOnPersianDate;
        private List<int> insuranceCompanyId;
        private int activePackageId;
        private string packageActivationLastDate;
        private string licenseApiKey;
        private string verifyRequestUrl;
        private bool onlinePayment;
        private bool cardToCardPayment;
        private bool bankTransferPayment;
        private bool cashOnDelivery;
        private bool bankTransferSameOnlinePaymentInfo;
        private int bankParamId;
        private string accountOwner;
        private string accountNumber;
        private string iban;
        private int cardBankParamId;
        private string cardAccountOwner;
        private string cardAccountNumber;
        private int bankTransferParamId;
        private string bankTransferAccountOwner;
        private string bankTransferAccountNumber;
        private string bankTransferIBAN;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("id")]
        public int Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("personId")]
        public string PersonId 
        { 
            get 
            {
                return this.personId; 
            } 
            set 
            {
                this.personId = value;
                onPropertyChanged("PersonId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("personalityType")]
        public int PersonalityType 
        { 
            get 
            {
                return this.personalityType; 
            } 
            set 
            {
                this.personalityType = value;
                onPropertyChanged("PersonalityType");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insuranceCentreType")]
        public int InsuranceCentreType 
        { 
            get 
            {
                return this.insuranceCentreType; 
            } 
            set 
            {
                this.insuranceCentreType = value;
                onPropertyChanged("InsuranceCentreType");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("registerStatus")]
        public int RegisterStatus 
        { 
            get 
            {
                return this.registerStatus; 
            } 
            set 
            {
                this.registerStatus = value;
                onPropertyChanged("RegisterStatus");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("centerName")]
        public string CenterName 
        { 
            get 
            {
                return this.centerName; 
            } 
            set 
            {
                this.centerName = value;
                onPropertyChanged("CenterName");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("centerCode")]
        public string CenterCode 
        { 
            get 
            {
                return this.centerCode; 
            } 
            set 
            {
                this.centerCode = value;
                onPropertyChanged("CenterCode");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("branchCount")]
        public string BranchCount 
        { 
            get 
            {
                return this.branchCount; 
            } 
            set 
            {
                this.branchCount = value;
                onPropertyChanged("BranchCount");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("registrationNumber")]
        public string RegistrationNumber 
        { 
            get 
            {
                return this.registrationNumber; 
            } 
            set 
            {
                this.registrationNumber = value;
                onPropertyChanged("RegistrationNumber");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("freeUseGoldenPackExpireDate")]
        public string FreeUseGoldenPackExpireDate 
        { 
            get 
            {
                return this.freeUseGoldenPackExpireDate; 
            } 
            set 
            {
                this.freeUseGoldenPackExpireDate = value;
                onPropertyChanged("FreeUseGoldenPackExpireDate");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("cityId")]
        public int CityId 
        { 
            get 
            {
                return this.cityId; 
            } 
            set 
            {
                this.cityId = value;
                onPropertyChanged("CityId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("cashPayment")]
        public bool CashPayment 
        { 
            get 
            {
                return this.cashPayment; 
            } 
            set 
            {
                this.cashPayment = value;
                onPropertyChanged("CashPayment");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("showInEasyBimeh")]
        public bool ShowInEasyBimeh 
        { 
            get 
            {
                return this.showInEasyBimeh; 
            } 
            set 
            {
                this.showInEasyBimeh = value;
                onPropertyChanged("ShowInEasyBimeh");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("installmentsPayment")]
        public bool InstallmentsPayment 
        { 
            get 
            {
                return this.installmentsPayment; 
            } 
            set 
            {
                this.installmentsPayment = value;
                onPropertyChanged("InstallmentsPayment");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("isInitialApplicant")]
        public bool IsInitialApplicant 
        { 
            get 
            {
                return this.isInitialApplicant; 
            } 
            set 
            {
                this.isInitialApplicant = value;
                onPropertyChanged("IsInitialApplicant");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("branchsCount")]
        public int BranchsCount 
        { 
            get 
            {
                return this.branchsCount; 
            } 
            set 
            {
                this.branchsCount = value;
                onPropertyChanged("BranchsCount");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("employeesCount")]
        public int EmployeesCount 
        { 
            get 
            {
                return this.employeesCount; 
            } 
            set 
            {
                this.employeesCount = value;
                onPropertyChanged("EmployeesCount");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("zoneId")]
        public string ZoneId 
        { 
            get 
            {
                return this.zoneId; 
            } 
            set 
            {
                this.zoneId = value;
                onPropertyChanged("ZoneId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("smsChargingStock")]
        public string SmsChargingStock 
        { 
            get 
            {
                return this.smsChargingStock; 
            } 
            set 
            {
                this.smsChargingStock = value;
                onPropertyChanged("SmsChargingStock");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("independentBranch")]
        public string IndependentBranch 
        { 
            get 
            {
                return this.independentBranch; 
            } 
            set 
            {
                this.independentBranch = value;
                onPropertyChanged("IndependentBranch");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("disableReason")]
        public string DisableReason 
        { 
            get 
            {
                return this.disableReason; 
            } 
            set 
            {
                this.disableReason = value;
                onPropertyChanged("DisableReason");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("termsConditions")]
        public string TermsConditions 
        { 
            get 
            {
                return this.termsConditions; 
            } 
            set 
            {
                this.termsConditions = value;
                onPropertyChanged("TermsConditions");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("disableReasonDescription")]
        public string DisableReasonDescription 
        { 
            get 
            {
                return this.disableReasonDescription; 
            } 
            set 
            {
                this.disableReasonDescription = value;
                onPropertyChanged("DisableReasonDescription");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("unlimitedAccount")]
        public string UnlimitedAccount 
        { 
            get 
            {
                return this.unlimitedAccount; 
            } 
            set 
            {
                this.unlimitedAccount = value;
                onPropertyChanged("UnlimitedAccount");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("whiteLabel")]
        public bool WhiteLabel 
        { 
            get 
            {
                return this.whiteLabel; 
            } 
            set 
            {
                this.whiteLabel = value;
                onPropertyChanged("WhiteLabel");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("phone")]
        public string Phone 
        { 
            get 
            {
                return this.phone; 
            } 
            set 
            {
                this.phone = value;
                onPropertyChanged("Phone");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("fax")]
        public string Fax 
        { 
            get 
            {
                return this.fax; 
            } 
            set 
            {
                this.fax = value;
                onPropertyChanged("Fax");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("address")]
        public string Address 
        { 
            get 
            {
                return this.address; 
            } 
            set 
            {
                this.address = value;
                onPropertyChanged("Address");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("zipCode")]
        public string ZipCode 
        { 
            get 
            {
                return this.zipCode; 
            } 
            set 
            {
                this.zipCode = value;
                onPropertyChanged("ZipCode");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("email")]
        public string Email 
        { 
            get 
            {
                return this.email; 
            } 
            set 
            {
                this.email = value;
                onPropertyChanged("Email");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("paymentUrl")]
        public string PaymentUrl 
        { 
            get 
            {
                return this.paymentUrl; 
            } 
            set 
            {
                this.paymentUrl = value;
                onPropertyChanged("PaymentUrl");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("callbackUrl")]
        public string CallbackUrl 
        { 
            get 
            {
                return this.callbackUrl; 
            } 
            set 
            {
                this.callbackUrl = value;
                onPropertyChanged("CallbackUrl");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("callbackUrlWhitelabel")]
        public string CallbackUrlWhitelabel 
        { 
            get 
            {
                return this.callbackUrlWhitelabel; 
            } 
            set 
            {
                this.callbackUrlWhitelabel = value;
                onPropertyChanged("CallbackUrlWhitelabel");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("webSite")]
        public string WebSite 
        { 
            get 
            {
                return this.webSite; 
            } 
            set 
            {
                this.webSite = value;
                onPropertyChanged("WebSite");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("latitude")]
        public double Latitude 
        { 
            get 
            {
                return this.latitude; 
            } 
            set 
            {
                this.latitude = value;
                onPropertyChanged("Latitude");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("longitude")]
        public double Longitude 
        { 
            get 
            {
                return this.longitude; 
            } 
            set 
            {
                this.longitude = value;
                onPropertyChanged("Longitude");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("isActive")]
        public bool IsActive 
        { 
            get 
            {
                return this.isActive; 
            } 
            set 
            {
                this.isActive = value;
                onPropertyChanged("IsActive");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insuranceCentreId")]
        public string InsuranceCentreId 
        { 
            get 
            {
                return this.insuranceCentreId; 
            } 
            set 
            {
                this.insuranceCentreId = value;
                onPropertyChanged("InsuranceCentreId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("cityRegionId")]
        public string CityRegionId 
        { 
            get 
            {
                return this.cityRegionId; 
            } 
            set 
            {
                this.cityRegionId = value;
                onPropertyChanged("CityRegionId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("provinceId")]
        public string ProvinceId 
        { 
            get 
            {
                return this.provinceId; 
            } 
            set 
            {
                this.provinceId = value;
                onPropertyChanged("ProvinceId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("cityName")]
        public string CityName 
        { 
            get 
            {
                return this.cityName; 
            } 
            set 
            {
                this.cityName = value;
                onPropertyChanged("CityName");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("metaMediaActivityLicenceId")]
        public int MetaMediaActivityLicenceId 
        { 
            get 
            {
                return this.metaMediaActivityLicenceId; 
            } 
            set 
            {
                this.metaMediaActivityLicenceId = value;
                onPropertyChanged("MetaMediaActivityLicenceId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("metaMediaActivityLicenceUrl")]
        public string MetaMediaActivityLicenceUrl 
        { 
            get 
            {
                return this.metaMediaActivityLicenceUrl; 
            } 
            set 
            {
                this.metaMediaActivityLicenceUrl = value;
                onPropertyChanged("MetaMediaActivityLicenceUrl");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("createOnPersianDate")]
        public string CreateOnPersianDate 
        { 
            get 
            {
                return this.createOnPersianDate; 
            } 
            set 
            {
                this.createOnPersianDate = value;
                onPropertyChanged("CreateOnPersianDate");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insuranceCompanyId")]
        public List<int> InsuranceCompanyId 
        { 
            get 
            {
                return this.insuranceCompanyId; 
            } 
            set 
            {
                this.insuranceCompanyId = value;
                onPropertyChanged("InsuranceCompanyId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("activePackageId")]
        public int ActivePackageId 
        { 
            get 
            {
                return this.activePackageId; 
            } 
            set 
            {
                this.activePackageId = value;
                onPropertyChanged("ActivePackageId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("packageActivationLastDate")]
        public string PackageActivationLastDate 
        { 
            get 
            {
                return this.packageActivationLastDate; 
            } 
            set 
            {
                this.packageActivationLastDate = value;
                onPropertyChanged("PackageActivationLastDate");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("licenseApiKey")]
        public string LicenseApiKey 
        { 
            get 
            {
                return this.licenseApiKey; 
            } 
            set 
            {
                this.licenseApiKey = value;
                onPropertyChanged("LicenseApiKey");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("verifyRequestUrl")]
        public string VerifyRequestUrl 
        { 
            get 
            {
                return this.verifyRequestUrl; 
            } 
            set 
            {
                this.verifyRequestUrl = value;
                onPropertyChanged("VerifyRequestUrl");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("onlinePayment")]
        public bool OnlinePayment 
        { 
            get 
            {
                return this.onlinePayment; 
            } 
            set 
            {
                this.onlinePayment = value;
                onPropertyChanged("OnlinePayment");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("cardToCardPayment")]
        public bool CardToCardPayment 
        { 
            get 
            {
                return this.cardToCardPayment; 
            } 
            set 
            {
                this.cardToCardPayment = value;
                onPropertyChanged("CardToCardPayment");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("bankTransferPayment")]
        public bool BankTransferPayment 
        { 
            get 
            {
                return this.bankTransferPayment; 
            } 
            set 
            {
                this.bankTransferPayment = value;
                onPropertyChanged("BankTransferPayment");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("cashOnDelivery")]
        public bool CashOnDelivery 
        { 
            get 
            {
                return this.cashOnDelivery; 
            } 
            set 
            {
                this.cashOnDelivery = value;
                onPropertyChanged("CashOnDelivery");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("bankTransferSameOnlinePaymentInfo")]
        public bool BankTransferSameOnlinePaymentInfo 
        { 
            get 
            {
                return this.bankTransferSameOnlinePaymentInfo; 
            } 
            set 
            {
                this.bankTransferSameOnlinePaymentInfo = value;
                onPropertyChanged("BankTransferSameOnlinePaymentInfo");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("bankParamId")]
        public int BankParamId 
        { 
            get 
            {
                return this.bankParamId; 
            } 
            set 
            {
                this.bankParamId = value;
                onPropertyChanged("BankParamId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("accountOwner")]
        public string AccountOwner 
        { 
            get 
            {
                return this.accountOwner; 
            } 
            set 
            {
                this.accountOwner = value;
                onPropertyChanged("AccountOwner");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("accountNumber")]
        public string AccountNumber 
        { 
            get 
            {
                return this.accountNumber; 
            } 
            set 
            {
                this.accountNumber = value;
                onPropertyChanged("AccountNumber");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("iban")]
        public string Iban 
        { 
            get 
            {
                return this.iban; 
            } 
            set 
            {
                this.iban = value;
                onPropertyChanged("Iban");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("cardBankParamId")]
        public int CardBankParamId 
        { 
            get 
            {
                return this.cardBankParamId; 
            } 
            set 
            {
                this.cardBankParamId = value;
                onPropertyChanged("CardBankParamId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("cardAccountOwner")]
        public string CardAccountOwner 
        { 
            get 
            {
                return this.cardAccountOwner; 
            } 
            set 
            {
                this.cardAccountOwner = value;
                onPropertyChanged("CardAccountOwner");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("cardAccountNumber")]
        public string CardAccountNumber 
        { 
            get 
            {
                return this.cardAccountNumber; 
            } 
            set 
            {
                this.cardAccountNumber = value;
                onPropertyChanged("CardAccountNumber");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("bankTransferParamId")]
        public int BankTransferParamId 
        { 
            get 
            {
                return this.bankTransferParamId; 
            } 
            set 
            {
                this.bankTransferParamId = value;
                onPropertyChanged("BankTransferParamId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("bankTransferAccountOwner")]
        public string BankTransferAccountOwner 
        { 
            get 
            {
                return this.bankTransferAccountOwner; 
            } 
            set 
            {
                this.bankTransferAccountOwner = value;
                onPropertyChanged("BankTransferAccountOwner");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("bankTransferAccountNumber")]
        public string BankTransferAccountNumber 
        { 
            get 
            {
                return this.bankTransferAccountNumber; 
            } 
            set 
            {
                this.bankTransferAccountNumber = value;
                onPropertyChanged("BankTransferAccountNumber");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("bankTransferIBAN")]
        public string BankTransferIBAN 
        { 
            get 
            {
                return this.bankTransferIBAN; 
            } 
            set 
            {
                this.bankTransferIBAN = value;
                onPropertyChanged("BankTransferIBAN");
            }
        }
    }
} 