/*
 * EasyBimehLanding.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using EasyBimehLanding.Standard;
using EasyBimehLanding.Standard.Utilities;


namespace EasyBimehLanding.Standard.Models
{
    public class InsuranceCentrePolicyTypes : BaseModel 
    {
        // These fields hold the values for the public properties.
        private int id;
        private string title;
        private string iconImage;
        private bool isActive;
        private string routingUrl;
        private string displayPriority;
        private int iconPosition;
        private string generalTerms;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("id")]
        public int Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("title")]
        public string Title 
        { 
            get 
            {
                return this.title; 
            } 
            set 
            {
                this.title = value;
                onPropertyChanged("Title");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("iconImage")]
        public string IconImage 
        { 
            get 
            {
                return this.iconImage; 
            } 
            set 
            {
                this.iconImage = value;
                onPropertyChanged("IconImage");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("isActive")]
        public bool IsActive 
        { 
            get 
            {
                return this.isActive; 
            } 
            set 
            {
                this.isActive = value;
                onPropertyChanged("IsActive");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("routingUrl")]
        public string RoutingUrl 
        { 
            get 
            {
                return this.routingUrl; 
            } 
            set 
            {
                this.routingUrl = value;
                onPropertyChanged("RoutingUrl");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("displayPriority")]
        public string DisplayPriority 
        { 
            get 
            {
                return this.displayPriority; 
            } 
            set 
            {
                this.displayPriority = value;
                onPropertyChanged("DisplayPriority");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("iconPosition")]
        public int IconPosition 
        { 
            get 
            {
                return this.iconPosition; 
            } 
            set 
            {
                this.iconPosition = value;
                onPropertyChanged("IconPosition");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("generalTerms")]
        public string GeneralTerms 
        { 
            get 
            {
                return this.generalTerms; 
            } 
            set 
            {
                this.generalTerms = value;
                onPropertyChanged("GeneralTerms");
            }
        }
    }
} 