/*
 * EasyBimehLanding.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using EasyBimehLanding.Standard;
using EasyBimehLanding.Standard.Utilities;


namespace EasyBimehLanding.Standard.Models
{
    public class InsuranceCentrePortal : BaseModel 
    {
        // These fields hold the values for the public properties.
        private int insuranceCentreId;
        private string centreName;
        private string subDomainName;
        private string title;
        private string subTitle;
        private string contactUs;
        private string aboutUs;
        private string ourService;
        private string termsConditions;
        private string copyright;
        private string headerTitle;
        private string headerBody;
        private string footerColor;
        private string backgroundColor;
        private bool licensed;
        private string defaultLogo;
        private string titleColor;
        private string subTitleColor;
        private string eTrustSymbol;
        private string digitalMediaOrganizerSymbol;
        private string googlePlus;
        private string telegram;
        private string instagram;
        private string faceBook;
        private string twitter;
        private string saturdayToWednesdayFromHour;
        private string saturdayToWednesdayToHour;
        private string thursdayFromHour;
        private string thursdayToHour;
        private string fridayFromHour;
        private string fridayToHour;
        private int metaMediaFileHeaderId;
        private string metaMediaFileHeaderUrl;
        private int metaMediaFileLogoId;
        private string metaMediaFileLogoUrl;
        private int metaMediaFileFaviconId;
        private string metaMediaFileFaviconUrl;
        private string metaMediaFileFooterId;
        private string metaMediaFileFooterUrl;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insuranceCentreId")]
        public int InsuranceCentreId 
        { 
            get 
            {
                return this.insuranceCentreId; 
            } 
            set 
            {
                this.insuranceCentreId = value;
                onPropertyChanged("InsuranceCentreId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("centreName")]
        public string CentreName 
        { 
            get 
            {
                return this.centreName; 
            } 
            set 
            {
                this.centreName = value;
                onPropertyChanged("CentreName");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("subDomainName")]
        public string SubDomainName 
        { 
            get 
            {
                return this.subDomainName; 
            } 
            set 
            {
                this.subDomainName = value;
                onPropertyChanged("SubDomainName");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("title")]
        public string Title 
        { 
            get 
            {
                return this.title; 
            } 
            set 
            {
                this.title = value;
                onPropertyChanged("Title");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("subTitle")]
        public string SubTitle 
        { 
            get 
            {
                return this.subTitle; 
            } 
            set 
            {
                this.subTitle = value;
                onPropertyChanged("SubTitle");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("contactUs")]
        public string ContactUs 
        { 
            get 
            {
                return this.contactUs; 
            } 
            set 
            {
                this.contactUs = value;
                onPropertyChanged("ContactUs");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("aboutUs")]
        public string AboutUs 
        { 
            get 
            {
                return this.aboutUs; 
            } 
            set 
            {
                this.aboutUs = value;
                onPropertyChanged("AboutUs");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ourService")]
        public string OurService 
        { 
            get 
            {
                return this.ourService; 
            } 
            set 
            {
                this.ourService = value;
                onPropertyChanged("OurService");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("termsConditions")]
        public string TermsConditions 
        { 
            get 
            {
                return this.termsConditions; 
            } 
            set 
            {
                this.termsConditions = value;
                onPropertyChanged("TermsConditions");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("copyright")]
        public string Copyright 
        { 
            get 
            {
                return this.copyright; 
            } 
            set 
            {
                this.copyright = value;
                onPropertyChanged("Copyright");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("headerTitle")]
        public string HeaderTitle 
        { 
            get 
            {
                return this.headerTitle; 
            } 
            set 
            {
                this.headerTitle = value;
                onPropertyChanged("HeaderTitle");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("headerBody")]
        public string HeaderBody 
        { 
            get 
            {
                return this.headerBody; 
            } 
            set 
            {
                this.headerBody = value;
                onPropertyChanged("HeaderBody");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("footerColor")]
        public string FooterColor 
        { 
            get 
            {
                return this.footerColor; 
            } 
            set 
            {
                this.footerColor = value;
                onPropertyChanged("FooterColor");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("backgroundColor")]
        public string BackgroundColor 
        { 
            get 
            {
                return this.backgroundColor; 
            } 
            set 
            {
                this.backgroundColor = value;
                onPropertyChanged("BackgroundColor");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("licensed")]
        public bool Licensed 
        { 
            get 
            {
                return this.licensed; 
            } 
            set 
            {
                this.licensed = value;
                onPropertyChanged("Licensed");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("defaultLogo")]
        public string DefaultLogo 
        { 
            get 
            {
                return this.defaultLogo; 
            } 
            set 
            {
                this.defaultLogo = value;
                onPropertyChanged("DefaultLogo");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("titleColor")]
        public string TitleColor 
        { 
            get 
            {
                return this.titleColor; 
            } 
            set 
            {
                this.titleColor = value;
                onPropertyChanged("TitleColor");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("subTitleColor")]
        public string SubTitleColor 
        { 
            get 
            {
                return this.subTitleColor; 
            } 
            set 
            {
                this.subTitleColor = value;
                onPropertyChanged("SubTitleColor");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("eTrustSymbol")]
        public string ETrustSymbol 
        { 
            get 
            {
                return this.eTrustSymbol; 
            } 
            set 
            {
                this.eTrustSymbol = value;
                onPropertyChanged("ETrustSymbol");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("digitalMediaOrganizerSymbol")]
        public string DigitalMediaOrganizerSymbol 
        { 
            get 
            {
                return this.digitalMediaOrganizerSymbol; 
            } 
            set 
            {
                this.digitalMediaOrganizerSymbol = value;
                onPropertyChanged("DigitalMediaOrganizerSymbol");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("googlePlus")]
        public string GooglePlus 
        { 
            get 
            {
                return this.googlePlus; 
            } 
            set 
            {
                this.googlePlus = value;
                onPropertyChanged("GooglePlus");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("telegram")]
        public string Telegram 
        { 
            get 
            {
                return this.telegram; 
            } 
            set 
            {
                this.telegram = value;
                onPropertyChanged("Telegram");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("instagram")]
        public string Instagram 
        { 
            get 
            {
                return this.instagram; 
            } 
            set 
            {
                this.instagram = value;
                onPropertyChanged("Instagram");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("faceBook")]
        public string FaceBook 
        { 
            get 
            {
                return this.faceBook; 
            } 
            set 
            {
                this.faceBook = value;
                onPropertyChanged("FaceBook");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("twitter")]
        public string Twitter 
        { 
            get 
            {
                return this.twitter; 
            } 
            set 
            {
                this.twitter = value;
                onPropertyChanged("Twitter");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("saturdayToWednesdayFromHour")]
        public string SaturdayToWednesdayFromHour 
        { 
            get 
            {
                return this.saturdayToWednesdayFromHour; 
            } 
            set 
            {
                this.saturdayToWednesdayFromHour = value;
                onPropertyChanged("SaturdayToWednesdayFromHour");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("saturdayToWednesdayToHour")]
        public string SaturdayToWednesdayToHour 
        { 
            get 
            {
                return this.saturdayToWednesdayToHour; 
            } 
            set 
            {
                this.saturdayToWednesdayToHour = value;
                onPropertyChanged("SaturdayToWednesdayToHour");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("thursdayFromHour")]
        public string ThursdayFromHour 
        { 
            get 
            {
                return this.thursdayFromHour; 
            } 
            set 
            {
                this.thursdayFromHour = value;
                onPropertyChanged("ThursdayFromHour");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("thursdayToHour")]
        public string ThursdayToHour 
        { 
            get 
            {
                return this.thursdayToHour; 
            } 
            set 
            {
                this.thursdayToHour = value;
                onPropertyChanged("ThursdayToHour");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("fridayFromHour")]
        public string FridayFromHour 
        { 
            get 
            {
                return this.fridayFromHour; 
            } 
            set 
            {
                this.fridayFromHour = value;
                onPropertyChanged("FridayFromHour");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("fridayToHour")]
        public string FridayToHour 
        { 
            get 
            {
                return this.fridayToHour; 
            } 
            set 
            {
                this.fridayToHour = value;
                onPropertyChanged("FridayToHour");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("metaMediaFileHeaderId")]
        public int MetaMediaFileHeaderId 
        { 
            get 
            {
                return this.metaMediaFileHeaderId; 
            } 
            set 
            {
                this.metaMediaFileHeaderId = value;
                onPropertyChanged("MetaMediaFileHeaderId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("metaMediaFileHeaderUrl")]
        public string MetaMediaFileHeaderUrl 
        { 
            get 
            {
                return this.metaMediaFileHeaderUrl; 
            } 
            set 
            {
                this.metaMediaFileHeaderUrl = value;
                onPropertyChanged("MetaMediaFileHeaderUrl");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("metaMediaFileLogoId")]
        public int MetaMediaFileLogoId 
        { 
            get 
            {
                return this.metaMediaFileLogoId; 
            } 
            set 
            {
                this.metaMediaFileLogoId = value;
                onPropertyChanged("MetaMediaFileLogoId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("metaMediaFileLogoUrl")]
        public string MetaMediaFileLogoUrl 
        { 
            get 
            {
                return this.metaMediaFileLogoUrl; 
            } 
            set 
            {
                this.metaMediaFileLogoUrl = value;
                onPropertyChanged("MetaMediaFileLogoUrl");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("metaMediaFileFaviconId")]
        public int MetaMediaFileFaviconId 
        { 
            get 
            {
                return this.metaMediaFileFaviconId; 
            } 
            set 
            {
                this.metaMediaFileFaviconId = value;
                onPropertyChanged("MetaMediaFileFaviconId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("metaMediaFileFaviconUrl")]
        public string MetaMediaFileFaviconUrl 
        { 
            get 
            {
                return this.metaMediaFileFaviconUrl; 
            } 
            set 
            {
                this.metaMediaFileFaviconUrl = value;
                onPropertyChanged("MetaMediaFileFaviconUrl");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("metaMediaFileFooterId")]
        public string MetaMediaFileFooterId 
        { 
            get 
            {
                return this.metaMediaFileFooterId; 
            } 
            set 
            {
                this.metaMediaFileFooterId = value;
                onPropertyChanged("MetaMediaFileFooterId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("metaMediaFileFooterUrl")]
        public string MetaMediaFileFooterUrl 
        { 
            get 
            {
                return this.metaMediaFileFooterUrl; 
            } 
            set 
            {
                this.metaMediaFileFooterUrl = value;
                onPropertyChanged("MetaMediaFileFooterUrl");
            }
        }
    }
} 