/*
 * EasyBimehLanding.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using EasyBimehLanding.Standard;
using EasyBimehLanding.Standard.Utilities;


namespace EasyBimehLanding.Standard.Models
{
    public class LiabilityDoctorInsurancePolicyExtendView : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string liabilityDoctorCoverageRateId;
        private string activityAreaParamId;
        private string expertiseParamId;
        private string commitmentCeilingParamId;
        private string insuranceRiskLevelId;
        private string currentInsuranceDeadline;
        private string riskLevelDiscountRate;
        private string physicalCommitment;
        private string discountRate;
        private string basePremium;
        private string allPremium;
        private string allExtraValues;
        private int insuranceCompanyDiscountRate;
        private int allDiscount;
        private int exchangePremium;
        private string doctorName;
        private string medicalSystemNO;
        private string address;
        private bool isResident;
        private bool isStudent;
        private string hasClinic;
        private string metaMediaMedicalSystemLicenseId;
        private string metaMediaMedicalSystemLicenseUrl;
        private string metaMediaNationalCardId;
        private string metaMediaNationalCardUrl;
        private string metaMediaCurrentInsurancePolicyId;
        private string metaMediaCurrentInsurancePolicyUrl;
        private string activityAreaEnumName;
        private string activityAreaTitle;
        private string expertiseTitle;
        private string docterStatusTitle;

        /// <summary>
        /// شناسه ی نرخ پوشش پزشکی
        /// </summary>
        [JsonProperty("liabilityDoctorCoverageRateId")]
        public string LiabilityDoctorCoverageRateId 
        { 
            get 
            {
                return this.liabilityDoctorCoverageRateId; 
            } 
            set 
            {
                this.liabilityDoctorCoverageRateId = value;
                onPropertyChanged("LiabilityDoctorCoverageRateId");
            }
        }

        /// <summary>
        /// شناسه ی دوره های فعالیت
        /// </summary>
        [JsonProperty("activityAreaParamId")]
        public string ActivityAreaParamId 
        { 
            get 
            {
                return this.activityAreaParamId; 
            } 
            set 
            {
                this.activityAreaParamId = value;
                onPropertyChanged("ActivityAreaParamId");
            }
        }

        /// <summary>
        /// شاسه ی تخصص
        /// </summary>
        [JsonProperty("expertiseParamId")]
        public string ExpertiseParamId 
        { 
            get 
            {
                return this.expertiseParamId; 
            } 
            set 
            {
                this.expertiseParamId = value;
                onPropertyChanged("ExpertiseParamId");
            }
        }

        /// <summary>
        /// شناسه ی سقف تعهد
        /// </summary>
        [JsonProperty("commitmentCeilingParamId")]
        public string CommitmentCeilingParamId 
        { 
            get 
            {
                return this.commitmentCeilingParamId; 
            } 
            set 
            {
                this.commitmentCeilingParamId = value;
                onPropertyChanged("CommitmentCeilingParamId");
            }
        }

        /// <summary>
        /// شناسه ی تخفیف
        /// </summary>
        [JsonProperty("insuranceRiskLevelId")]
        public string InsuranceRiskLevelId 
        { 
            get 
            {
                return this.insuranceRiskLevelId; 
            } 
            set 
            {
                this.insuranceRiskLevelId = value;
                onPropertyChanged("InsuranceRiskLevelId");
            }
        }

        /// <summary>
        /// تاریخ پایان بیمه نامه
        /// </summary>
        [JsonProperty("currentInsuranceDeadline")]
        public string CurrentInsuranceDeadline 
        { 
            get 
            {
                return this.currentInsuranceDeadline; 
            } 
            set 
            {
                this.currentInsuranceDeadline = value;
                onPropertyChanged("CurrentInsuranceDeadline");
            }
        }

        /// <summary>
        /// نرخ تخفیف پوشش
        /// </summary>
        [JsonProperty("riskLevelDiscountRate")]
        public string RiskLevelDiscountRate 
        { 
            get 
            {
                return this.riskLevelDiscountRate; 
            } 
            set 
            {
                this.riskLevelDiscountRate = value;
                onPropertyChanged("RiskLevelDiscountRate");
            }
        }

        /// <summary>
        /// خسارت جانی
        /// </summary>
        [JsonProperty("physicalCommitment")]
        public string PhysicalCommitment 
        { 
            get 
            {
                return this.physicalCommitment; 
            } 
            set 
            {
                this.physicalCommitment = value;
                onPropertyChanged("PhysicalCommitment");
            }
        }

        /// <summary>
        /// نرخ تخفیف
        /// </summary>
        [JsonProperty("discountRate")]
        public string DiscountRate 
        { 
            get 
            {
                return this.discountRate; 
            } 
            set 
            {
                this.discountRate = value;
                onPropertyChanged("DiscountRate");
            }
        }

        /// <summary>
        /// پوشش پایه
        /// </summary>
        [JsonProperty("basePremium")]
        public string BasePremium 
        { 
            get 
            {
                return this.basePremium; 
            } 
            set 
            {
                this.basePremium = value;
                onPropertyChanged("BasePremium");
            }
        }

        /// <summary>
        /// پوشش ها
        /// </summary>
        [JsonProperty("allPremium")]
        public string AllPremium 
        { 
            get 
            {
                return this.allPremium; 
            } 
            set 
            {
                this.allPremium = value;
                onPropertyChanged("AllPremium");
            }
        }

        /// <summary>
        /// اطلاعات اضافه
        /// </summary>
        [JsonProperty("allExtraValues")]
        public string AllExtraValues 
        { 
            get 
            {
                return this.allExtraValues; 
            } 
            set 
            {
                this.allExtraValues = value;
                onPropertyChanged("AllExtraValues");
            }
        }

        /// <summary>
        /// نرخ تخفیف شرکت بیمه
        /// </summary>
        [JsonProperty("insuranceCompanyDiscountRate")]
        public int InsuranceCompanyDiscountRate 
        { 
            get 
            {
                return this.insuranceCompanyDiscountRate; 
            } 
            set 
            {
                this.insuranceCompanyDiscountRate = value;
                onPropertyChanged("InsuranceCompanyDiscountRate");
            }
        }

        /// <summary>
        /// لیست تخفیفات
        /// </summary>
        [JsonProperty("allDiscount")]
        public int AllDiscount 
        { 
            get 
            {
                return this.allDiscount; 
            } 
            set 
            {
                this.allDiscount = value;
                onPropertyChanged("AllDiscount");
            }
        }

        /// <summary>
        /// نوع ارز حق بیمه
        /// </summary>
        [JsonProperty("exchangePremium")]
        public int ExchangePremium 
        { 
            get 
            {
                return this.exchangePremium; 
            } 
            set 
            {
                this.exchangePremium = value;
                onPropertyChanged("ExchangePremium");
            }
        }

        /// <summary>
        /// نام پزشک
        /// </summary>
        [JsonProperty("doctorName")]
        public string DoctorName 
        { 
            get 
            {
                return this.doctorName; 
            } 
            set 
            {
                this.doctorName = value;
                onPropertyChanged("DoctorName");
            }
        }

        /// <summary>
        /// شماره ی نظام پزشکی
        /// </summary>
        [JsonProperty("medicalSystemNO")]
        public string MedicalSystemNO 
        { 
            get 
            {
                return this.medicalSystemNO; 
            } 
            set 
            {
                this.medicalSystemNO = value;
                onPropertyChanged("MedicalSystemNO");
            }
        }

        /// <summary>
        /// آدرس
        /// </summary>
        [JsonProperty("address")]
        public string Address 
        { 
            get 
            {
                return this.address; 
            } 
            set 
            {
                this.address = value;
                onPropertyChanged("Address");
            }
        }

        /// <summary>
        /// آیا رزیدنت است؟
        /// </summary>
        [JsonProperty("isResident")]
        public bool IsResident 
        { 
            get 
            {
                return this.isResident; 
            } 
            set 
            {
                this.isResident = value;
                onPropertyChanged("IsResident");
            }
        }

        /// <summary>
        /// آیا دانشجو است؟
        /// </summary>
        [JsonProperty("isStudent")]
        public bool IsStudent 
        { 
            get 
            {
                return this.isStudent; 
            } 
            set 
            {
                this.isStudent = value;
                onPropertyChanged("IsStudent");
            }
        }

        /// <summary>
        /// دارای مطب؟
        /// </summary>
        [JsonProperty("hasClinic")]
        public string HasClinic 
        { 
            get 
            {
                return this.hasClinic; 
            } 
            set 
            {
                this.hasClinic = value;
                onPropertyChanged("HasClinic");
            }
        }

        /// <summary>
        /// شناسه ی گواهی نظام پزشکی
        /// </summary>
        [JsonProperty("metaMediaMedicalSystemLicenseId")]
        public string MetaMediaMedicalSystemLicenseId 
        { 
            get 
            {
                return this.metaMediaMedicalSystemLicenseId; 
            } 
            set 
            {
                this.metaMediaMedicalSystemLicenseId = value;
                onPropertyChanged("MetaMediaMedicalSystemLicenseId");
            }
        }

        /// <summary>
        /// آدرس گواهی نظام پزشکی
        /// </summary>
        [JsonProperty("metaMediaMedicalSystemLicenseUrl")]
        public string MetaMediaMedicalSystemLicenseUrl 
        { 
            get 
            {
                return this.metaMediaMedicalSystemLicenseUrl; 
            } 
            set 
            {
                this.metaMediaMedicalSystemLicenseUrl = value;
                onPropertyChanged("MetaMediaMedicalSystemLicenseUrl");
            }
        }

        /// <summary>
        /// شناسه ی کارت ملی
        /// </summary>
        [JsonProperty("metaMediaNationalCardId")]
        public string MetaMediaNationalCardId 
        { 
            get 
            {
                return this.metaMediaNationalCardId; 
            } 
            set 
            {
                this.metaMediaNationalCardId = value;
                onPropertyChanged("MetaMediaNationalCardId");
            }
        }

        /// <summary>
        /// آدرس کارت ملی
        /// </summary>
        [JsonProperty("metaMediaNationalCardUrl")]
        public string MetaMediaNationalCardUrl 
        { 
            get 
            {
                return this.metaMediaNationalCardUrl; 
            } 
            set 
            {
                this.metaMediaNationalCardUrl = value;
                onPropertyChanged("MetaMediaNationalCardUrl");
            }
        }

        /// <summary>
        /// شناسه ی بیمه نامه ی کنونی
        /// </summary>
        [JsonProperty("metaMediaCurrentInsurancePolicyId")]
        public string MetaMediaCurrentInsurancePolicyId 
        { 
            get 
            {
                return this.metaMediaCurrentInsurancePolicyId; 
            } 
            set 
            {
                this.metaMediaCurrentInsurancePolicyId = value;
                onPropertyChanged("MetaMediaCurrentInsurancePolicyId");
            }
        }

        /// <summary>
        /// آدرس بیمه نامه ی کنونی
        /// </summary>
        [JsonProperty("metaMediaCurrentInsurancePolicyUrl")]
        public string MetaMediaCurrentInsurancePolicyUrl 
        { 
            get 
            {
                return this.metaMediaCurrentInsurancePolicyUrl; 
            } 
            set 
            {
                this.metaMediaCurrentInsurancePolicyUrl = value;
                onPropertyChanged("MetaMediaCurrentInsurancePolicyUrl");
            }
        }

        /// <summary>
        /// شناسه ی دوره های بیمه نامه
        /// </summary>
        [JsonProperty("activityAreaEnumName")]
        public string ActivityAreaEnumName 
        { 
            get 
            {
                return this.activityAreaEnumName; 
            } 
            set 
            {
                this.activityAreaEnumName = value;
                onPropertyChanged("ActivityAreaEnumName");
            }
        }

        /// <summary>
        /// نام دوره ی بیمه نامه
        /// </summary>
        [JsonProperty("activityAreaTitle")]
        public string ActivityAreaTitle 
        { 
            get 
            {
                return this.activityAreaTitle; 
            } 
            set 
            {
                this.activityAreaTitle = value;
                onPropertyChanged("ActivityAreaTitle");
            }
        }

        /// <summary>
        /// نام تخصص
        /// </summary>
        [JsonProperty("expertiseTitle")]
        public string ExpertiseTitle 
        { 
            get 
            {
                return this.expertiseTitle; 
            } 
            set 
            {
                this.expertiseTitle = value;
                onPropertyChanged("ExpertiseTitle");
            }
        }

        /// <summary>
        /// وضعیت پزشک
        /// </summary>
        [JsonProperty("docterStatusTitle")]
        public string DocterStatusTitle 
        { 
            get 
            {
                return this.docterStatusTitle; 
            } 
            set 
            {
                this.docterStatusTitle = value;
                onPropertyChanged("DocterStatusTitle");
            }
        }
    }
} 