/*
 * EasyBimehLanding.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using EasyBimehLanding.Standard;
using EasyBimehLanding.Standard.Utilities;


namespace EasyBimehLanding.Standard.Models
{
    public class SpecialPlan : BaseModel 
    {
        // These fields hold the values for the public properties.
        private int key;
        private int count;
        private string title;
        private int policyType;
        private string display;
        private int iconPosition;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("key")]
        public int Key 
        { 
            get 
            {
                return this.key; 
            } 
            set 
            {
                this.key = value;
                onPropertyChanged("Key");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("count")]
        public int Count 
        { 
            get 
            {
                return this.count; 
            } 
            set 
            {
                this.count = value;
                onPropertyChanged("Count");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("title")]
        public string Title 
        { 
            get 
            {
                return this.title; 
            } 
            set 
            {
                this.title = value;
                onPropertyChanged("Title");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("policyType")]
        public int PolicyType 
        { 
            get 
            {
                return this.policyType; 
            } 
            set 
            {
                this.policyType = value;
                onPropertyChanged("PolicyType");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("display")]
        public string Display 
        { 
            get 
            {
                return this.display; 
            } 
            set 
            {
                this.display = value;
                onPropertyChanged("Display");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("iconPosition")]
        public int IconPosition 
        { 
            get 
            {
                return this.iconPosition; 
            } 
            set 
            {
                this.iconPosition = value;
                onPropertyChanged("IconPosition");
            }
        }
    }
} 