/*
 * EasyBimehLanding.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using EasyBimehLanding.Standard;
using EasyBimehLanding.Standard.Utilities;


namespace EasyBimehLanding.Standard.Models
{
    public class TargetSite : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string name;
        private string assemblyName;
        private string className;
        private string signature;
        private string signature2;
        private int memberType;
        private string genericArguments;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Name")]
        public string Name 
        { 
            get 
            {
                return this.name; 
            } 
            set 
            {
                this.name = value;
                onPropertyChanged("Name");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("AssemblyName")]
        public string AssemblyName 
        { 
            get 
            {
                return this.assemblyName; 
            } 
            set 
            {
                this.assemblyName = value;
                onPropertyChanged("AssemblyName");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ClassName")]
        public string ClassName 
        { 
            get 
            {
                return this.className; 
            } 
            set 
            {
                this.className = value;
                onPropertyChanged("ClassName");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Signature")]
        public string Signature 
        { 
            get 
            {
                return this.signature; 
            } 
            set 
            {
                this.signature = value;
                onPropertyChanged("Signature");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Signature2")]
        public string Signature2 
        { 
            get 
            {
                return this.signature2; 
            } 
            set 
            {
                this.signature2 = value;
                onPropertyChanged("Signature2");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("MemberType")]
        public int MemberType 
        { 
            get 
            {
                return this.memberType; 
            } 
            set 
            {
                this.memberType = value;
                onPropertyChanged("MemberType");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("GenericArguments")]
        public string GenericArguments 
        { 
            get 
            {
                return this.genericArguments; 
            } 
            set 
            {
                this.genericArguments = value;
                onPropertyChanged("GenericArguments");
            }
        }
    }
} 