/*
 * EasyBimehLanding.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using EasyBimehLanding.Standard;
using EasyBimehLanding.Standard.Utilities;


namespace EasyBimehLanding.Standard.Models
{
    public class TrackingDamageStatus : BaseModel 
    {
        // These fields hold the values for the public properties.
        private List<Models.TrackingDamageFile> trackingDamageFile;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("trackingDamageFile")]
        public List<Models.TrackingDamageFile> TrackingDamageFile 
        { 
            get 
            {
                return this.trackingDamageFile; 
            } 
            set 
            {
                this.trackingDamageFile = value;
                onPropertyChanged("TrackingDamageFile");
            }
        }
    }
} 