/*
 * EasyBimehLanding.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using EasyBimehLanding.Standard;
using EasyBimehLanding.Standard.Utilities;


namespace EasyBimehLanding.Standard.Models
{
    public class TrackingDamageRequest : BaseModel 
    {
        // These fields hold the values for the public properties.
        private int personalityType;
        private List<Models.TrackingDamageStatus> trackingDamageStatus;
        private string description;
        private int insuranceTypeId;
        private int insuranceCompanyId;
        private string insurancePolicyNumber;
        private string damageType;
        private string name;
        private string nationalCode;
        private string mobile;
        private string insuredProfile;
        private string subDomain;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("personalityType")]
        public int PersonalityType 
        { 
            get 
            {
                return this.personalityType; 
            } 
            set 
            {
                this.personalityType = value;
                onPropertyChanged("PersonalityType");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("trackingDamageStatus")]
        public List<Models.TrackingDamageStatus> TrackingDamageStatus 
        { 
            get 
            {
                return this.trackingDamageStatus; 
            } 
            set 
            {
                this.trackingDamageStatus = value;
                onPropertyChanged("TrackingDamageStatus");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("description")]
        public string Description 
        { 
            get 
            {
                return this.description; 
            } 
            set 
            {
                this.description = value;
                onPropertyChanged("Description");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insuranceTypeId")]
        public int InsuranceTypeId 
        { 
            get 
            {
                return this.insuranceTypeId; 
            } 
            set 
            {
                this.insuranceTypeId = value;
                onPropertyChanged("InsuranceTypeId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insuranceCompanyId")]
        public int InsuranceCompanyId 
        { 
            get 
            {
                return this.insuranceCompanyId; 
            } 
            set 
            {
                this.insuranceCompanyId = value;
                onPropertyChanged("InsuranceCompanyId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insurancePolicyNumber")]
        public string InsurancePolicyNumber 
        { 
            get 
            {
                return this.insurancePolicyNumber; 
            } 
            set 
            {
                this.insurancePolicyNumber = value;
                onPropertyChanged("InsurancePolicyNumber");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("damageType")]
        public string DamageType 
        { 
            get 
            {
                return this.damageType; 
            } 
            set 
            {
                this.damageType = value;
                onPropertyChanged("DamageType");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("name")]
        public string Name 
        { 
            get 
            {
                return this.name; 
            } 
            set 
            {
                this.name = value;
                onPropertyChanged("Name");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("nationalCode")]
        public string NationalCode 
        { 
            get 
            {
                return this.nationalCode; 
            } 
            set 
            {
                this.nationalCode = value;
                onPropertyChanged("NationalCode");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("mobile")]
        public string Mobile 
        { 
            get 
            {
                return this.mobile; 
            } 
            set 
            {
                this.mobile = value;
                onPropertyChanged("Mobile");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insuredProfile")]
        public string InsuredProfile 
        { 
            get 
            {
                return this.insuredProfile; 
            } 
            set 
            {
                this.insuredProfile = value;
                onPropertyChanged("InsuredProfile");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("subDomain")]
        public string SubDomain 
        { 
            get 
            {
                return this.subDomain; 
            } 
            set 
            {
                this.subDomain = value;
                onPropertyChanged("SubDomain");
            }
        }
    }
} 