/*
 * EasyBimehLanding.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using EasyBimehLanding.Standard;
using EasyBimehLanding.Standard.Utilities;


namespace EasyBimehLanding.Standard.Models
{
    public class TrackingDamageStatusTrackingCode : BaseModel 
    {
        // These fields hold the values for the public properties.
        private int id;
        private int trackingDamageId;
        private string description;
        private int trackingDamageStatus;
        private List<Models.TrackingDamageFileTrackinCode> trackingDamageFile;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("id")]
        public int Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("trackingDamageId")]
        public int TrackingDamageId 
        { 
            get 
            {
                return this.trackingDamageId; 
            } 
            set 
            {
                this.trackingDamageId = value;
                onPropertyChanged("TrackingDamageId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("description")]
        public string Description 
        { 
            get 
            {
                return this.description; 
            } 
            set 
            {
                this.description = value;
                onPropertyChanged("Description");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("trackingDamageStatus")]
        public int TrackingDamageStatus 
        { 
            get 
            {
                return this.trackingDamageStatus; 
            } 
            set 
            {
                this.trackingDamageStatus = value;
                onPropertyChanged("TrackingDamageStatus");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("trackingDamageFile")]
        public List<Models.TrackingDamageFileTrackinCode> TrackingDamageFile 
        { 
            get 
            {
                return this.trackingDamageFile; 
            } 
            set 
            {
                this.trackingDamageFile = value;
                onPropertyChanged("TrackingDamageFile");
            }
        }
    }
} 