/*
 * EasyBimehLanding.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using EasyBimehLanding.Standard;
using EasyBimehLanding.Standard.Utilities;


namespace EasyBimehLanding.Standard.Models
{
    public class TrackingCode : BaseModel 
    {
        // These fields hold the values for the public properties.
        private int id;
        private int insuranceTypeId;
        private int insuranceCentreId;
        private string insuranceCentreName;
        private int insuranceCompanyId;
        private string insuranceCompanyTitle;
        private string insurancePolicyNumber;
        private int personalityType;
        private string damageType;
        private string name;
        private string nationalCode;
        private string mobile;
        private string insuredProfile;
        private string refrencedUser;
        private string referenceCount;
        private string trackingCode;
        private string paymentType;
        private string paymentDate;
        private string paymentPersianDate;
        private string subDomain;
        private string insuranceTypeTitle;
        private string createOn;
        private string updateOn;
        private string createOnPersianDate;
        private string updateOnPersianDate;
        private List<Models.TrackingDamageStatusTrackingCode> trackingDamageStatus;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("id")]
        public int Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insuranceTypeId")]
        public int InsuranceTypeId 
        { 
            get 
            {
                return this.insuranceTypeId; 
            } 
            set 
            {
                this.insuranceTypeId = value;
                onPropertyChanged("InsuranceTypeId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insuranceCentreId")]
        public int InsuranceCentreId 
        { 
            get 
            {
                return this.insuranceCentreId; 
            } 
            set 
            {
                this.insuranceCentreId = value;
                onPropertyChanged("InsuranceCentreId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insuranceCentreName")]
        public string InsuranceCentreName 
        { 
            get 
            {
                return this.insuranceCentreName; 
            } 
            set 
            {
                this.insuranceCentreName = value;
                onPropertyChanged("InsuranceCentreName");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insuranceCompanyId")]
        public int InsuranceCompanyId 
        { 
            get 
            {
                return this.insuranceCompanyId; 
            } 
            set 
            {
                this.insuranceCompanyId = value;
                onPropertyChanged("InsuranceCompanyId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insuranceCompanyTitle")]
        public string InsuranceCompanyTitle 
        { 
            get 
            {
                return this.insuranceCompanyTitle; 
            } 
            set 
            {
                this.insuranceCompanyTitle = value;
                onPropertyChanged("InsuranceCompanyTitle");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insurancePolicyNumber")]
        public string InsurancePolicyNumber 
        { 
            get 
            {
                return this.insurancePolicyNumber; 
            } 
            set 
            {
                this.insurancePolicyNumber = value;
                onPropertyChanged("InsurancePolicyNumber");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("personalityType")]
        public int PersonalityType 
        { 
            get 
            {
                return this.personalityType; 
            } 
            set 
            {
                this.personalityType = value;
                onPropertyChanged("PersonalityType");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("damageType")]
        public string DamageType 
        { 
            get 
            {
                return this.damageType; 
            } 
            set 
            {
                this.damageType = value;
                onPropertyChanged("DamageType");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("name")]
        public string Name 
        { 
            get 
            {
                return this.name; 
            } 
            set 
            {
                this.name = value;
                onPropertyChanged("Name");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("nationalCode")]
        public string NationalCode 
        { 
            get 
            {
                return this.nationalCode; 
            } 
            set 
            {
                this.nationalCode = value;
                onPropertyChanged("NationalCode");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("mobile")]
        public string Mobile 
        { 
            get 
            {
                return this.mobile; 
            } 
            set 
            {
                this.mobile = value;
                onPropertyChanged("Mobile");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insuredProfile")]
        public string InsuredProfile 
        { 
            get 
            {
                return this.insuredProfile; 
            } 
            set 
            {
                this.insuredProfile = value;
                onPropertyChanged("InsuredProfile");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("refrencedUser")]
        public string RefrencedUser 
        { 
            get 
            {
                return this.refrencedUser; 
            } 
            set 
            {
                this.refrencedUser = value;
                onPropertyChanged("RefrencedUser");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("referenceCount")]
        public string ReferenceCount 
        { 
            get 
            {
                return this.referenceCount; 
            } 
            set 
            {
                this.referenceCount = value;
                onPropertyChanged("ReferenceCount");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("trackingCode")]
        public string TrackingCodeProp 
        { 
            get 
            {
                return this.trackingCode; 
            } 
            set 
            {
                this.trackingCode = value;
                onPropertyChanged("TrackingCodeProp");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("paymentType")]
        public string PaymentType 
        { 
            get 
            {
                return this.paymentType; 
            } 
            set 
            {
                this.paymentType = value;
                onPropertyChanged("PaymentType");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("paymentDate")]
        public string PaymentDate 
        { 
            get 
            {
                return this.paymentDate; 
            } 
            set 
            {
                this.paymentDate = value;
                onPropertyChanged("PaymentDate");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("paymentPersianDate")]
        public string PaymentPersianDate 
        { 
            get 
            {
                return this.paymentPersianDate; 
            } 
            set 
            {
                this.paymentPersianDate = value;
                onPropertyChanged("PaymentPersianDate");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("subDomain")]
        public string SubDomain 
        { 
            get 
            {
                return this.subDomain; 
            } 
            set 
            {
                this.subDomain = value;
                onPropertyChanged("SubDomain");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insuranceTypeTitle")]
        public string InsuranceTypeTitle 
        { 
            get 
            {
                return this.insuranceTypeTitle; 
            } 
            set 
            {
                this.insuranceTypeTitle = value;
                onPropertyChanged("InsuranceTypeTitle");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("createOn")]
        public string CreateOn 
        { 
            get 
            {
                return this.createOn; 
            } 
            set 
            {
                this.createOn = value;
                onPropertyChanged("CreateOn");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("updateOn")]
        public string UpdateOn 
        { 
            get 
            {
                return this.updateOn; 
            } 
            set 
            {
                this.updateOn = value;
                onPropertyChanged("UpdateOn");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("createOnPersianDate")]
        public string CreateOnPersianDate 
        { 
            get 
            {
                return this.createOnPersianDate; 
            } 
            set 
            {
                this.createOnPersianDate = value;
                onPropertyChanged("CreateOnPersianDate");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("updateOnPersianDate")]
        public string UpdateOnPersianDate 
        { 
            get 
            {
                return this.updateOnPersianDate; 
            } 
            set 
            {
                this.updateOnPersianDate = value;
                onPropertyChanged("UpdateOnPersianDate");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("trackingDamageStatus")]
        public List<Models.TrackingDamageStatusTrackingCode> TrackingDamageStatus 
        { 
            get 
            {
                return this.trackingDamageStatus; 
            } 
            set 
            {
                this.trackingDamageStatus = value;
                onPropertyChanged("TrackingDamageStatus");
            }
        }
    }
} 