/*
 * EasyBimehLanding.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using EasyBimehLanding.Standard;
using EasyBimehLanding.Standard.Utilities;


namespace EasyBimehLanding.Standard.Models
{
    public class TravelInsurance : BaseModel 
    {
        // These fields hold the values for the public properties.
        private bool hasPlan;
        private bool isSamanInsurance;
        private List<Models.Zone> zones;
        private List<Models.TravelDuration> travelDurations;
        private List<Models.TravelAge> travelAges;
        private List<Models.Province> provinces;
        private List<string> cities;
        private List<string> cityRegions;
        private List<Models.ShippingType> shippingTypes;
        private List<Models.PostType> postTypes;
        private Models.InsuranceDataTravelInsurance insuranceData;
        private Models.InsurancePolicyCondition insurancePolicyCondition;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("hasPlan")]
        public bool HasPlan 
        { 
            get 
            {
                return this.hasPlan; 
            } 
            set 
            {
                this.hasPlan = value;
                onPropertyChanged("HasPlan");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("isSamanInsurance")]
        public bool IsSamanInsurance 
        { 
            get 
            {
                return this.isSamanInsurance; 
            } 
            set 
            {
                this.isSamanInsurance = value;
                onPropertyChanged("IsSamanInsurance");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("zones")]
        public List<Models.Zone> Zones 
        { 
            get 
            {
                return this.zones; 
            } 
            set 
            {
                this.zones = value;
                onPropertyChanged("Zones");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("travelDurations")]
        public List<Models.TravelDuration> TravelDurations 
        { 
            get 
            {
                return this.travelDurations; 
            } 
            set 
            {
                this.travelDurations = value;
                onPropertyChanged("TravelDurations");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("travelAges")]
        public List<Models.TravelAge> TravelAges 
        { 
            get 
            {
                return this.travelAges; 
            } 
            set 
            {
                this.travelAges = value;
                onPropertyChanged("TravelAges");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("provinces")]
        public List<Models.Province> Provinces 
        { 
            get 
            {
                return this.provinces; 
            } 
            set 
            {
                this.provinces = value;
                onPropertyChanged("Provinces");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("cities")]
        public List<string> Cities 
        { 
            get 
            {
                return this.cities; 
            } 
            set 
            {
                this.cities = value;
                onPropertyChanged("Cities");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("cityRegions")]
        public List<string> CityRegions 
        { 
            get 
            {
                return this.cityRegions; 
            } 
            set 
            {
                this.cityRegions = value;
                onPropertyChanged("CityRegions");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("shippingTypes")]
        public List<Models.ShippingType> ShippingTypes 
        { 
            get 
            {
                return this.shippingTypes; 
            } 
            set 
            {
                this.shippingTypes = value;
                onPropertyChanged("ShippingTypes");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("postTypes")]
        public List<Models.PostType> PostTypes 
        { 
            get 
            {
                return this.postTypes; 
            } 
            set 
            {
                this.postTypes = value;
                onPropertyChanged("PostTypes");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insuranceData")]
        public Models.InsuranceDataTravelInsurance InsuranceData 
        { 
            get 
            {
                return this.insuranceData; 
            } 
            set 
            {
                this.insuranceData = value;
                onPropertyChanged("InsuranceData");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insurancePolicyCondition")]
        public Models.InsurancePolicyCondition InsurancePolicyCondition 
        { 
            get 
            {
                return this.insurancePolicyCondition; 
            } 
            set 
            {
                this.insurancePolicyCondition = value;
                onPropertyChanged("InsurancePolicyCondition");
            }
        }
    }
} 