/*
 * EasyBimehLanding.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using EasyBimehLanding.Standard;
using EasyBimehLanding.Standard.Utilities;


namespace EasyBimehLanding.Standard.Models
{
    public class TravelInsurancePolicyExtend : BaseModel 
    {
        // These fields hold the values for the public properties.
        private int insurancePolicyId;
        private string travelDurationParam;
        private int passengersCount;
        private string birthDate;
        private string birthDatePersian;
        private int riskLevelDiscount;
        private string basePremium;
        private string allPremium;
        private int insuranceCompanyDiscountRate;
        private int insuranceCompanyDiscount;
        private int insuranceCentreDiscount;
        private int coupenDiscount;
        private int allDiscount;
        private int exchangePremium;
        private string travelRatePlanId;
        private string planTitle;
        private string travelInsurancePolicyExtendAges;
        private string travelInsurancePolicyExtendPassengers;
        private string zoneIds;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insurancePolicyId")]
        public int InsurancePolicyId 
        { 
            get 
            {
                return this.insurancePolicyId; 
            } 
            set 
            {
                this.insurancePolicyId = value;
                onPropertyChanged("InsurancePolicyId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("travelDurationParam")]
        public string TravelDurationParam 
        { 
            get 
            {
                return this.travelDurationParam; 
            } 
            set 
            {
                this.travelDurationParam = value;
                onPropertyChanged("TravelDurationParam");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("passengersCount")]
        public int PassengersCount 
        { 
            get 
            {
                return this.passengersCount; 
            } 
            set 
            {
                this.passengersCount = value;
                onPropertyChanged("PassengersCount");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("birthDate")]
        public string BirthDate 
        { 
            get 
            {
                return this.birthDate; 
            } 
            set 
            {
                this.birthDate = value;
                onPropertyChanged("BirthDate");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("birthDatePersian")]
        public string BirthDatePersian 
        { 
            get 
            {
                return this.birthDatePersian; 
            } 
            set 
            {
                this.birthDatePersian = value;
                onPropertyChanged("BirthDatePersian");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("riskLevelDiscount")]
        public int RiskLevelDiscount 
        { 
            get 
            {
                return this.riskLevelDiscount; 
            } 
            set 
            {
                this.riskLevelDiscount = value;
                onPropertyChanged("RiskLevelDiscount");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("basePremium")]
        public string BasePremium 
        { 
            get 
            {
                return this.basePremium; 
            } 
            set 
            {
                this.basePremium = value;
                onPropertyChanged("BasePremium");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("allPremium")]
        public string AllPremium 
        { 
            get 
            {
                return this.allPremium; 
            } 
            set 
            {
                this.allPremium = value;
                onPropertyChanged("AllPremium");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insuranceCompanyDiscountRate")]
        public int InsuranceCompanyDiscountRate 
        { 
            get 
            {
                return this.insuranceCompanyDiscountRate; 
            } 
            set 
            {
                this.insuranceCompanyDiscountRate = value;
                onPropertyChanged("InsuranceCompanyDiscountRate");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insuranceCompanyDiscount")]
        public int InsuranceCompanyDiscount 
        { 
            get 
            {
                return this.insuranceCompanyDiscount; 
            } 
            set 
            {
                this.insuranceCompanyDiscount = value;
                onPropertyChanged("InsuranceCompanyDiscount");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("insuranceCentreDiscount")]
        public int InsuranceCentreDiscount 
        { 
            get 
            {
                return this.insuranceCentreDiscount; 
            } 
            set 
            {
                this.insuranceCentreDiscount = value;
                onPropertyChanged("InsuranceCentreDiscount");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("coupenDiscount")]
        public int CoupenDiscount 
        { 
            get 
            {
                return this.coupenDiscount; 
            } 
            set 
            {
                this.coupenDiscount = value;
                onPropertyChanged("CoupenDiscount");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("allDiscount")]
        public int AllDiscount 
        { 
            get 
            {
                return this.allDiscount; 
            } 
            set 
            {
                this.allDiscount = value;
                onPropertyChanged("AllDiscount");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("exchangePremium")]
        public int ExchangePremium 
        { 
            get 
            {
                return this.exchangePremium; 
            } 
            set 
            {
                this.exchangePremium = value;
                onPropertyChanged("ExchangePremium");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("travelRatePlanId")]
        public string TravelRatePlanId 
        { 
            get 
            {
                return this.travelRatePlanId; 
            } 
            set 
            {
                this.travelRatePlanId = value;
                onPropertyChanged("TravelRatePlanId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("planTitle")]
        public string PlanTitle 
        { 
            get 
            {
                return this.planTitle; 
            } 
            set 
            {
                this.planTitle = value;
                onPropertyChanged("PlanTitle");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("travelInsurancePolicyExtendAges")]
        public string TravelInsurancePolicyExtendAges 
        { 
            get 
            {
                return this.travelInsurancePolicyExtendAges; 
            } 
            set 
            {
                this.travelInsurancePolicyExtendAges = value;
                onPropertyChanged("TravelInsurancePolicyExtendAges");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("travelInsurancePolicyExtendPassengers")]
        public string TravelInsurancePolicyExtendPassengers 
        { 
            get 
            {
                return this.travelInsurancePolicyExtendPassengers; 
            } 
            set 
            {
                this.travelInsurancePolicyExtendPassengers = value;
                onPropertyChanged("TravelInsurancePolicyExtendPassengers");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("zoneIds")]
        public string ZoneIds 
        { 
            get 
            {
                return this.zoneIds; 
            } 
            set 
            {
                this.zoneIds = value;
                onPropertyChanged("ZoneIds");
            }
        }
    }
} 