/*
 * EasyBimehLanding.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using EasyBimehLanding.Standard;
using EasyBimehLanding.Standard.Utilities;


namespace EasyBimehLanding.Standard.Models
{
    public class Upload : BaseModel 
    {
        // These fields hold the values for the public properties.
        private int id;
        private int metaMediaDirectoryId;
        private string title;
        private string alt;
        private string fileName;
        private string passwordHash;
        private string isActive;
        private string expireOn;
        private string fileLibraryLabelParam;
        private string fileSize;
        private string fileSizeValue;
        private string fileUrl;
        private string fileThumbnailUrl;
        private string expireOnPersianDate;
        private string updateOn;
        private string createOn;
        private string createOnPersianDate;
        private string updateOnPersianDate;
        private string filePath;

        /// <summary>
        /// شناسه ی فایل
        /// </summary>
        [JsonProperty("id")]
        public int Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// شناسه ی دایرکتوری فایل
        /// </summary>
        [JsonProperty("metaMediaDirectoryId")]
        public int MetaMediaDirectoryId 
        { 
            get 
            {
                return this.metaMediaDirectoryId; 
            } 
            set 
            {
                this.metaMediaDirectoryId = value;
                onPropertyChanged("MetaMediaDirectoryId");
            }
        }

        /// <summary>
        /// عنوان
        /// </summary>
        [JsonProperty("title")]
        public string Title 
        { 
            get 
            {
                return this.title; 
            } 
            set 
            {
                this.title = value;
                onPropertyChanged("Title");
            }
        }

        /// <summary>
        /// توضیح فایل
        /// </summary>
        [JsonProperty("alt")]
        public string Alt 
        { 
            get 
            {
                return this.alt; 
            } 
            set 
            {
                this.alt = value;
                onPropertyChanged("Alt");
            }
        }

        /// <summary>
        /// نام فایل
        /// </summary>
        [JsonProperty("fileName")]
        public string FileName 
        { 
            get 
            {
                return this.fileName; 
            } 
            set 
            {
                this.fileName = value;
                onPropertyChanged("FileName");
            }
        }

        /// <summary>
        /// پسورد فایل
        /// </summary>
        [JsonProperty("passwordHash")]
        public string PasswordHash 
        { 
            get 
            {
                return this.passwordHash; 
            } 
            set 
            {
                this.passwordHash = value;
                onPropertyChanged("PasswordHash");
            }
        }

        /// <summary>
        /// وضعیت اکتیو بودن فایل
        /// </summary>
        [JsonProperty("isActive")]
        public string IsActive 
        { 
            get 
            {
                return this.isActive; 
            } 
            set 
            {
                this.isActive = value;
                onPropertyChanged("IsActive");
            }
        }

        /// <summary>
        /// زمان انقضای فایل
        /// </summary>
        [JsonProperty("expireOn")]
        public string ExpireOn 
        { 
            get 
            {
                return this.expireOn; 
            } 
            set 
            {
                this.expireOn = value;
                onPropertyChanged("ExpireOn");
            }
        }

        /// <summary>
        /// لیبل دسته بندی فایل
        /// </summary>
        [JsonProperty("fileLibraryLabelParam")]
        public string FileLibraryLabelParam 
        { 
            get 
            {
                return this.fileLibraryLabelParam; 
            } 
            set 
            {
                this.fileLibraryLabelParam = value;
                onPropertyChanged("FileLibraryLabelParam");
            }
        }

        /// <summary>
        /// اندازه ی فایل
        /// </summary>
        [JsonProperty("fileSize")]
        public string FileSize 
        { 
            get 
            {
                return this.fileSize; 
            } 
            set 
            {
                this.fileSize = value;
                onPropertyChanged("FileSize");
            }
        }

        /// <summary>
        /// اندازه ی فایل
        /// </summary>
        [JsonProperty("fileSizeValue")]
        public string FileSizeValue 
        { 
            get 
            {
                return this.fileSizeValue; 
            } 
            set 
            {
                this.fileSizeValue = value;
                onPropertyChanged("FileSizeValue");
            }
        }

        /// <summary>
        /// آدرس فایل
        /// </summary>
        [JsonProperty("fileUrl")]
        public string FileUrl 
        { 
            get 
            {
                return this.fileUrl; 
            } 
            set 
            {
                this.fileUrl = value;
                onPropertyChanged("FileUrl");
            }
        }

        /// <summary>
        /// آدرس پیش نمایش فایل
        /// </summary>
        [JsonProperty("fileThumbnailUrl")]
        public string FileThumbnailUrl 
        { 
            get 
            {
                return this.fileThumbnailUrl; 
            } 
            set 
            {
                this.fileThumbnailUrl = value;
                onPropertyChanged("FileThumbnailUrl");
            }
        }

        /// <summary>
        /// تاریخ انقضای شمسی
        /// </summary>
        [JsonProperty("expireOnPersianDate")]
        public string ExpireOnPersianDate 
        { 
            get 
            {
                return this.expireOnPersianDate; 
            } 
            set 
            {
                this.expireOnPersianDate = value;
                onPropertyChanged("ExpireOnPersianDate");
            }
        }

        /// <summary>
        /// تاریخ بروز رسانی فایل
        /// </summary>
        [JsonProperty("updateOn")]
        public string UpdateOn 
        { 
            get 
            {
                return this.updateOn; 
            } 
            set 
            {
                this.updateOn = value;
                onPropertyChanged("UpdateOn");
            }
        }

        /// <summary>
        /// تاریخ ثبت فایل
        /// </summary>
        [JsonProperty("createOn")]
        public string CreateOn 
        { 
            get 
            {
                return this.createOn; 
            } 
            set 
            {
                this.createOn = value;
                onPropertyChanged("CreateOn");
            }
        }

        /// <summary>
        /// تاریخ ثبت فایل شمسی
        /// </summary>
        [JsonProperty("createOnPersianDate")]
        public string CreateOnPersianDate 
        { 
            get 
            {
                return this.createOnPersianDate; 
            } 
            set 
            {
                this.createOnPersianDate = value;
                onPropertyChanged("CreateOnPersianDate");
            }
        }

        /// <summary>
        /// تاریخ بروز رسانی فایل شمسی
        /// </summary>
        [JsonProperty("updateOnPersianDate")]
        public string UpdateOnPersianDate 
        { 
            get 
            {
                return this.updateOnPersianDate; 
            } 
            set 
            {
                this.updateOnPersianDate = value;
                onPropertyChanged("UpdateOnPersianDate");
            }
        }

        /// <summary>
        /// آدرس دایرکتوری فایل
        /// </summary>
        [JsonProperty("filePath")]
        public string FilePath 
        { 
            get 
            {
                return this.filePath; 
            } 
            set 
            {
                this.filePath = value;
                onPropertyChanged("FilePath");
            }
        }
    }
} 