/*
 * EasyBimehLanding.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using EasyBimehLanding.Standard;
using EasyBimehLanding.Standard.Utilities;


namespace EasyBimehLanding.Standard.Models
{
    public class VideoGallery : BaseModel 
    {
        // These fields hold the values for the public properties.
        private int id;
        private int galleryType;
        private string title;
        private string alt;
        private string description;
        private bool isActive;
        private bool isMain;
        private bool isAttachFile;
        private string sortPriority;
        private string createOnPersianDate;
        private int metaMediaFileId;
        private string metaMediaFileUrl;
        private string metaMediaFileThumbnailUrl;
        private List<string> popupImageGalleryies;
        private List<string> galleryDetails;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("id")]
        public int Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("galleryType")]
        public int GalleryType 
        { 
            get 
            {
                return this.galleryType; 
            } 
            set 
            {
                this.galleryType = value;
                onPropertyChanged("GalleryType");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("title")]
        public string Title 
        { 
            get 
            {
                return this.title; 
            } 
            set 
            {
                this.title = value;
                onPropertyChanged("Title");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("alt")]
        public string Alt 
        { 
            get 
            {
                return this.alt; 
            } 
            set 
            {
                this.alt = value;
                onPropertyChanged("Alt");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("description")]
        public string Description 
        { 
            get 
            {
                return this.description; 
            } 
            set 
            {
                this.description = value;
                onPropertyChanged("Description");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("isActive")]
        public bool IsActive 
        { 
            get 
            {
                return this.isActive; 
            } 
            set 
            {
                this.isActive = value;
                onPropertyChanged("IsActive");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("isMain")]
        public bool IsMain 
        { 
            get 
            {
                return this.isMain; 
            } 
            set 
            {
                this.isMain = value;
                onPropertyChanged("IsMain");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("isAttachFile")]
        public bool IsAttachFile 
        { 
            get 
            {
                return this.isAttachFile; 
            } 
            set 
            {
                this.isAttachFile = value;
                onPropertyChanged("IsAttachFile");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("sortPriority")]
        public string SortPriority 
        { 
            get 
            {
                return this.sortPriority; 
            } 
            set 
            {
                this.sortPriority = value;
                onPropertyChanged("SortPriority");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("createOnPersianDate")]
        public string CreateOnPersianDate 
        { 
            get 
            {
                return this.createOnPersianDate; 
            } 
            set 
            {
                this.createOnPersianDate = value;
                onPropertyChanged("CreateOnPersianDate");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("metaMediaFileId")]
        public int MetaMediaFileId 
        { 
            get 
            {
                return this.metaMediaFileId; 
            } 
            set 
            {
                this.metaMediaFileId = value;
                onPropertyChanged("MetaMediaFileId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("metaMediaFileUrl")]
        public string MetaMediaFileUrl 
        { 
            get 
            {
                return this.metaMediaFileUrl; 
            } 
            set 
            {
                this.metaMediaFileUrl = value;
                onPropertyChanged("MetaMediaFileUrl");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("metaMediaFileThumbnailUrl")]
        public string MetaMediaFileThumbnailUrl 
        { 
            get 
            {
                return this.metaMediaFileThumbnailUrl; 
            } 
            set 
            {
                this.metaMediaFileThumbnailUrl = value;
                onPropertyChanged("MetaMediaFileThumbnailUrl");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("popupImageGalleryies")]
        public List<string> PopupImageGalleryies 
        { 
            get 
            {
                return this.popupImageGalleryies; 
            } 
            set 
            {
                this.popupImageGalleryies = value;
                onPropertyChanged("PopupImageGalleryies");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("galleryDetails")]
        public List<string> GalleryDetails 
        { 
            get 
            {
                return this.galleryDetails; 
            } 
            set 
            {
                this.galleryDetails = value;
                onPropertyChanged("GalleryDetails");
            }
        }
    }
} 